---
sidebar: sidebar 
permalink: support/get-help.html 
keywords: how to get help with astra control, how to get support with astra control, astra control knowledgebase, netapp technical support, discord, phone, web, ticket, contact support, support ticket, support bundle 
summary: 'NetApp은 다양한 방법으로 Astra Control을 지원합니다. 기술 자료(KB) 기사 및 불화 채널 같은 광범위한 무료 셀프 지원 옵션이 24x7 제공됩니다. Astra Control 계정에는 웹 발권 서비스를 통한 원격 기술 지원이 포함되어 있습니다.' 
---
= 도움을 받으십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/support/


[role="lead"]
NetApp은 다양한 방법으로 Astra Control을 지원합니다. 기술 자료(KB) 기사 및 불화 채널 같은 광범위한 무료 셀프 지원 옵션이 24x7 제공됩니다. Astra Control 계정에는 웹 발권 서비스를 통한 원격 기술 지원이 포함되어 있습니다.


IMPORTANT: Astra Control Center에 대한 평가판 라이센스가 있는 경우 기술 지원을 받을 수 있습니다. 그러나 NSS(NetApp Support Site)를 통한 케이스 생성은 사용할 수 없습니다. 피드백 옵션을 통해 지원을 받거나 불협화음을 셀프 서비스로 사용할 수 있습니다.

먼저 해야 합니다 link:../get-started/add-license.html["NetApp 일련 번호에 대한 지원을 활성화합니다"] 이러한 비 셀프 서비스 지원 옵션을 사용하려면 NetApp NSS(Support Site) SSO 계정은 케이스 관리와 함께 채팅 및 웹 티켓팅에 필요합니다.



== 자체 지원 옵션

기본 메뉴에서 * 지원 * 탭을 선택하면 Astra Control Center UI에서 지원 옵션에 액세스할 수 있습니다.

이러한 옵션은 24x7 무료로 제공됩니다.

* https://kb.netapp.com/Cloud/Astra/Control["* 기술 문서 사용 * (로그인 필요)"^]Astra Control과 관련된 문서, FAQ 또는 고장 수리 정보를 검색합니다.
* * 제품 설명서를 참조하십시오 * : 현재 보고 있는 문서 사이트입니다.
* https://discord.gg/NetApp["* 불화를 통한 도움 받기*"^]: Pub 카테고리의 Astra로 이동하여 동료 및 전문가와 교류하십시오.
* * 지원 케이스 생성 *: 문제 해결을 위해 NetApp 지원에 제공할 지원 번들을 생성합니다.
* * Astra Control에 대한 피드백 제공 *: astra.feedback@netapp.com 으로 이메일을 보내 귀하의 생각, 아이디어 또는 우려 사항을 알려 주십시오.




== NetApp Support에 매일 예약된 지원 번들 업로드를 활성화합니다

Astra Control Center를 설치하는 동안(지정된 경우 `enrolled: true` 용 `autoSupport` Astra Control Center CR(사용자 지정 리소스) 파일 (`astra_control_center.yaml`), 일별 지원 번들은 에 자동으로 업로드됩니다 https://mysupport.netapp.com/site/["NetApp Support 사이트"^].



== NetApp 지원에 제공할 지원 번들을 생성합니다

Astra Control Center를 사용하면 관리자가 NetApp 지원에 유용한 정보, 로그, Astra 구축의 모든 구성 요소에 대한 이벤트, 메트릭, 관리 중인 클러스터와 앱에 대한 토폴로지 정보 등 번들을 생성할 수 있습니다. 인터넷에 연결되어 있는 경우 Astra Control Center UI에서 직접 NSS(NetApp Support Site)에 지원 번들을 업로드할 수 있습니다.


NOTE: Astra Control Center에서 번들을 생성하는 데 걸리는 시간은 Astra Control Center 설치 크기와 요청된 지원 번들의 매개 변수에 따라 다릅니다. 지원 번들을 요청할 때 지정한 기간은 번들을 생성하는 데 걸리는 시간을 나타냅니다(예: 기간이 짧을수록 번들 생성 속도가 빠름).

.시작하기 전에
NSS에 번들을 업로드하는 데 프록시 연결이 필요한지 여부를 확인합니다. 프록시 연결이 필요한 경우 Astra Control Center가 프록시 서버를 사용하도록 구성되어 있는지 확인합니다.

. 계정 * > * 연결 * 을 선택합니다.
. 연결 설정 * 에서 프록시 설정을 확인하십시오.


.단계
. Astra Control Center UI의 * 지원 * 페이지에 나열된 라이센스 일련 번호를 사용하여 NSS 포털에서 케이스를 생성합니다.
. Astra Control Center UI를 사용하여 지원 번들을 생성하려면 다음 단계를 수행하십시오.
+
.. 지원 * 페이지의 지원 번들 타일에서 * 생성 * 을 선택합니다.
.. 지원 번들 생성 * 창에서 기간을 선택합니다.
+
빠른 시간 또는 사용자 지정 시간 계획 중에서 선택할 수 있습니다.

+

NOTE: 사용자 지정 날짜 범위를 선택하고 날짜 범위 동안 사용자 지정 기간을 지정할 수 있습니다.

.. 선택한 후 * Confirm * (확인 *)을 선택합니다.
.. 생성 시 NetApp Support 사이트에 번들 업로드 * 확인란을 선택합니다.
.. Generate Bundle * 를 선택합니다.
+
지원 번들이 준비되면 알림 영역의 * 계정 * > * 알림 * 페이지, * 활동 * 페이지 및 알림 목록(UI 오른쪽 상단에 있는 아이콘을 선택하여 액세스 가능)에 알림이 표시됩니다.

+
생성에 실패하면 Generate Bundle(번들 생성) 페이지에 아이콘이 나타납니다. 메시지를 보려면 아이콘을 선택합니다.






TIP: UI 오른쪽 위에 있는 알림 아이콘은 지원 번들과 관련된 이벤트(예: 번들이 성공적으로 생성된 경우, 번들 생성에 실패한 경우, 번들을 업로드할 수 없는 경우, 번들을 다운로드할 수 없는 경우 등)에 대한 정보를 제공합니다.



=== 공기 박기 설치가 있는 경우

공기 교환 설치가 있는 경우 지원 번들을 생성한 후 다음 단계를 수행하십시오. 번들을 다운로드할 수 있는 경우 * Support * 페이지의 * Support Bundles * 섹션에서 * Generate * 옆에 다운로드 아이콘이 나타납니다.

.단계
. 번들을 로컬로 다운로드하려면 다운로드 아이콘을 선택합니다.
. NSS에 번들을 수동으로 업로드합니다.
+
다음 방법 중 하나를 사용하여 이 작업을 수행할 수 있습니다.

+
** 사용 https://upload.netapp.com/sg["NetApp 인증된 파일 업로드(로그인 필요)"^].
** NSS에서 케이스에 번들을 직접 부착합니다.
** Digital Advisor 사용




[discrete]
== 자세한 내용을 확인하십시오

* https://kb.netapp.com/Advice_and_Troubleshooting/Miscellaneous/How_to_upload_a_file_to_NetApp["NetApp에 파일을 업로드하는 방법(로그인 필요)"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9["파일을 NetApp에 수동으로 업로드하는 방법(로그인 필요)"^]

