= Astra Control Center를 다운로드하고 압축을 풉니다
:allow-uri-read: 




== Astra Control Center를 다운로드하고 압축을 풉니다

다음 위치 중 하나에서 Astra Control Center 이미지를 다운로드하십시오.

* * Astra 컨트롤 서비스 이미지 레지스트리 *: Astra 컨트롤 센터 이미지에 로컬 레지스트리를 사용하지 않거나 NetApp Support 사이트에서 번들 다운로드보다 이 방법을 선호하는 경우 이 옵션을 사용합니다.
* * NetApp Support 사이트 *: Astra 컨트롤 센터 이미지와 함께 로컬 레지스트리를 사용하는 경우 이 옵션을 사용합니다.


[role="tabbed-block"]
====
.Astra Control 이미지 레지스트리
--
. Astra Control Service에 로그인합니다.
. 대시보드에서 * Astra Control의 자가 관리형 인스턴스 배포 * 를 선택합니다.
. 지침에 따라 Astra Control 이미지 레지스트리에 로그인하고 Astra Control Center 설치 이미지를 가져온 다음 이미지를 추출합니다.


--
.NetApp Support 사이트
--
. Astra Control Center가 포함된 번들을 다운로드합니다 (`astra-control-center-[version].tar.gz`)를 선택합니다 https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Astra Control Center 다운로드 페이지"^].
. (권장되지만 선택 사항) Astra Control Center용 인증서 및 서명 번들을 다운로드합니다 (`astra-control-center-certs-[version].tar.gz`)를 클릭하여 번들 서명을 확인합니다.
+
[source, console]
----
tar -vxzf astra-control-center-certs-[version].tar.gz
----
+
[source, console]
----
openssl dgst -sha256 -verify certs/AstraControlCenter-public.pub -signature certs/astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----
+
출력이 표시됩니다 `Verified OK` 확인 성공 후.

. Astra Control Center 번들에서 이미지를 추출합니다.
+
[source, console]
----
tar -vxzf astra-control-center-[version].tar.gz
----


--
====