= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Astra Trident 운영자
--
. https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html#step-1-download-the-trident-installer-package["Astra Trident 설치 프로그램을 다운로드하여 압축을 풉니다"^].
. Astra Trident를 아직 설치하지 않았거나 원본 Astra Trident 구축에서 연산자를 제거한 경우 다음 단계를 완료하십시오.
+
.. CRD 생성:
+
[source, console]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----
.. 트라이덴트 네임스페이스를 만듭니다 (`kubectl create namespace trident`) 또는 트리덴트 네임스페이스가 여전히 존재하는지 확인합니다 (`kubectl get all -n trident`)를 클릭합니다. 네임스페이스가 제거된 경우 다시 만듭니다.


. Astra Trident를 24.02.0으로 업데이트:
+

NOTE: Kubernetes 1.24 이하 버전을 실행하는 클러스터의 경우, 를 사용합니다 `bundle_pre_1_25.yaml`. Kubernetes 1.25 이상을 실행하는 클러스터의 경우 를 사용합니다 `bundle_post_1_25.yaml`.

+
[source, console]
----
kubectl -n trident apply -f trident-installer/deploy/<bundle-name.yaml>
----
. Astra Trident가 실행 중인지 확인합니다.
+
[source, console]
----
kubectl get torc -n trident
----
+
응답:

+
[listing]
----
NAME      AGE
trident   21m
----
. [[pull-secrets]]] 비밀을 사용하는 레지스트리가 있는 경우 Astra Control Provisioner 이미지를 가져오는 데 사용할 비밀을 만듭니다.
+
[source, console]
----
kubectl create secret docker-registry <secret_name> -n trident --docker-server=<my_custom_registry> --docker-username=<username> --docker-password=<token>
----
. TridentOrchestrator CR을 편집하고 다음과 같이 편집합니다.
+
[source, console]
----
kubectl edit torc trident -n trident
----
+
.. Astra Trident 이미지에 대한 사용자 지정 레지스트리 위치를 설정하거나 Astra Control 레지스트리에서 가져옵니다 (`tridentImage: <my_custom_registry>/trident:24.02.0` 또는 `tridentImage: netapp/trident:24.02.0`)를 클릭합니다.
.. Astra Control Provisioner를 활성화합니다 (`enableACP: true`)를 클릭합니다.
.. Astra Control Provisioner 이미지의 사용자 지정 레지스트리 위치를 설정하거나 Astra Control 레지스트리에서 가져옵니다 (`acpImage: <my_custom_registry>/trident-acp:24.02.0` 또는 `acpImage: cr.astra.netapp.io/astra/trident-acp:24.02.0`)를 클릭합니다.
.. 를 설정했는지 확인합니다 <<pull-secrets,이미지 풀 암호>> 이 절차의 앞부분에서 여기에서 설정할 수 있습니다 (`imagePullSecrets: - <secret_name>`)를 클릭합니다. 이전 단계에서 설정한 것과 동일한 이름 암호 이름을 사용합니다.


+
[listing, subs="+quotes"]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  *tridentImage: <registry>/trident:24.02.0*
  *enableACP: true*
  *acpImage: <registry>/trident-acp:24.02.0*
  *imagePullSecrets:
  - <secret_name>*
----
. 파일을 저장하고 종료합니다. 배포 프로세스가 자동으로 시작됩니다.
. 운영자, 배포 및 복제 세트가 생성되었는지 확인합니다.
+
[source, console]
----
kubectl get all -n trident
----
+

IMPORTANT: Kubernetes 클러스터에는 운영자의 인스턴스 * 하나가 있어야 합니다. Astra Trident 연산자를 여러 번 구축해서는 안 됩니다.

. 를 확인합니다 `trident-acp` 컨테이너가 실행 중이며 `acpVersion` 있습니다 `24.02.0` 의 상태입니다 `Installed`:
+
[source, console]
----
kubectl get torc -o yaml
----
+
응답:

+
[listing]
----
status:
  acpVersion: 24.02.0
  currentInstallationParams:
    ...
    acpImage: <registry>/trident-acp:24.02.0
    enableACP: "true"
    ...
  ...
  status: Installed
----


--
.tridentctl 을 선택합니다
--
. https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-tridentctl.html#step-1-download-the-trident-installer-package["Astra Trident 설치 프로그램을 다운로드하여 압축을 풉니다"^].
. https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-tridentctl.html["기존 Astra Trident가 있는 경우 이를 호스팅하는 클러스터에서 제거합니다"^].
. Astra Control Provisioner를 사용하도록 설정된 Astra Trident를 설치합니다 (`--enable-acp=true`):
+
[source, console]
----
./tridentctl -n trident install --enable-acp=true --acp-image=mycustomregistry/trident-acp:24.02
----
. Astra Control Provisioner가 활성화되었는지 확인합니다.
+
[source, console]
----
./tridentctl -n trident version
----
+
응답:

+
[listing]
----
+----------------+----------------+-------------+ | SERVER VERSION | CLIENT VERSION | ACP VERSION | +----------------+----------------+-------------+ | 24.02.0 | 24.02.0 | 24.02.0. | +----------------+----------------+-------------+
----


--
.헬름
--
. Astra Trident 23.07.1 이하를 설치한 경우 https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html#uninstall-a-trident-operator-installation["설치 제거"^] 작업자 및 기타 구성품
. Kubernetes 클러스터에서 1.24 이전 버전을 실행 중인 경우 psp:
+
[listing]
----
kubectl delete psp tridentoperatorpod
----
. Astra Trident Helm 리포지토리를 추가합니다.
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 제어 차트 업데이트:
+
[listing]
----
helm repo update netapp-trident
----
+
응답:

+
[listing]
----
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "netapp-trident" chart repository
Update Complete. ⎈Happy Helming!⎈
----
. 영상을 나열합니다.
+
[listing]
----
./tridentctl images -n trident
----
+
응답:

+
[listing]
----
| v1.28.0            | netapp/trident:24.02.0|
|                    | docker.io/netapp/trident-autosupport:24.02|
|                    | registry.k8s.io/sig-storage/csi-provisioner:v4.0.0|
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.5.0|
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.9.3|
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3|
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0 |
|                    | netapp/trident-operator:24.02.0 (optional)
----
. 트라이덴트 - 운전자 24.02.0을 사용할 수 있는지 확인합니다.
+
[listing]
----
helm search repo netapp-trident/trident-operator --versions
----
+
응답:

+
[listing]
----
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
netapp-trident/trident-operator 100.2402.0      24.02.0         A
----
. 사용 `helm install` 을 클릭하고 다음 설정을 포함하는 옵션 중 하나를 실행합니다.
+
** 배포 위치의 이름입니다
** Astra Trident 버전
** Astra Control Provisioner 이미지의 이름
** Provisioner를 활성화하는 플래그입니다
** (선택 사항) 로컬 레지스트리 경로입니다. 로컬 레지스트리를 사용하는 경우, 을(를) 참조하십시오 https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Trident 이미지"^] 하나의 레지스트리 또는 다른 레지스트리에 있을 수 있지만 모든 CSI 이미지는 동일한 레지스트리에 있어야 합니다.
** Trident 네임스페이스




.옵션
* 레지스트리가 없는 이미지


[listing]
----
helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=cr.astra.netapp.io/astra/trident-acp:24.02.0 --set enableACP=true --set operatorImage=netapp/trident-operator:24.02.0 --set tridentAutosupportImage=docker.io/netapp/trident-autosupport:24.02 --set tridentImage=netapp/trident:24.02.0 --namespace trident
----
* 하나 이상의 레지스트리에 있는 이미지


[listing]
----
helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=<your-registry>:<acp image> --set enableACP=true --set imageRegistry=<your-registry>/sig-storage --set operatorImage=netapp/trident-operator:24.02.0 --set tridentAutosupportImage=docker.io/netapp/trident-autosupport:24.02 --set tridentImage=netapp/trident:24.02.0 --namespace trident
----
을 사용할 수 있습니다 `helm list` 이름, 네임스페이스, 차트, 상태, 앱 버전과 같은 설치 세부 정보를 검토하려면 수정본 번호.

[NOTE]
====
Helm을 사용하여 Trident를 구축하는 데 문제가 있는 경우 다음 명령을 실행하여 Astra Trident를 완전히 제거합니다.

[listing]
----
./tridentctl uninstall -n trident
----
* 하지 마십시오 * https://docs.netapp.com/us-en/trident/troubleshooting.html#completely-remove-astra-trident-and-crds["Astra Trident CRD를 완전히 제거합니다"^] 설치 제거의 일부로 Astra Control Provisioner를 다시 활성화하려고 합니다.

====
--
====