---
sidebar: sidebar 
permalink: concepts/choose-class-and-size.html 
keywords: service level, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance, persistent, volume, kubernetes, containers 
summary: Astra Control Center는 ONTAP 스토리지 또는 Astra Data Store 스토리지 클래스에서 지원하는 Trident 스토리지 클래스를 지원합니다. 또한, 스토리지 클래스와 영구 볼륨 크기가 성능 목표를 달성하는 데 어떤 도움이 되는지 이해해야 합니다. 
---
= 스토리지 클래스 및 영구 볼륨 크기
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Astra Control Center는 스토리지 백엔드로 ONTAP 또는 Astra Data Store를 지원합니다. 스토리지 클래스 및 영구 볼륨(PV) 크기가 성과 목표를 달성하는 데 어떤 도움이 되는지 이해해야 합니다.



== 개요

Astra Control Center는 다음을 지원합니다.

* * Astra Data Store 스토리지에서 지원하는 Trident 스토리지 클래스 *: 하나 이상의 Astra Data Store 클러스터를 수동으로 설치한 경우, Astra Control Center는 이러한 클러스터를 가져오고 토폴로지(노드, 디스크)와 다양한 상태를 검색할 수 있는 기능을 제공합니다.
+
Astra Control Center는 Astra Data Store 구성의 기본 Kubernetes 클러스터, Kubernetes 클러스터가 속한 클라우드, Astra Data Store에서 프로비저닝한 영구 볼륨, 해당 내부 볼륨의 이름, 영구 볼륨을 사용하는 애플리케이션, 앱이 포함된 클러스터를 표시합니다.

* * ONTAP 스토리지에서 지원하는 Trident 스토리지 클래스 *: ONTAP 백엔드를 사용하는 경우, Astra 제어 센터에서 ONTAP 백엔드를 가져와 다양한 모니터링 정보를 보고할 수 있습니다.



NOTE: Trident 스토리지 클래스는 Astra Control Center 외부에서 사전 구성되어 있어야 합니다.



== 스토리지 클래스

Astra Control Center에 클러스터를 추가하면 해당 클러스터에서 이전에 구성된 스토리지 클래스 중 하나를 기본 스토리지 클래스로 선택하라는 메시지가 표시됩니다. 이 스토리지 클래스는 영구 볼륨 클레임(PVC)에 지정된 저장소 클래스가 없을 때 사용됩니다. 기본 스토리지 클래스는 Astra Control Center 내에서 언제든지 변경할 수 있으며, PVC 또는 H제어 차트 내에서 스토리지 클래스의 이름을 지정하여 언제든지 모든 스토리지 클래스를 사용할 수 있습니다.

Astra Data Store 스토리지 백엔드와 통합된 Astra Control Center를 사용하는 경우 설치 후 스토리지 클래스가 정의되지 않습니다. Trident 기본 스토리지 클래스를 생성하여 스토리지 백엔드에 적용해야 합니다. 을 참조하십시오 https://docs.netapp.com/us-en/astra-data-store/get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend["Astra Data Store를 시작하는 중입니다"] 기본 Astra Data Store 스토리지 클래스를 생성합니다.



== 를 참조하십시오

* https://docs.netapp.com/us-en/trident/index.html["Astra Trident 문서"^]

