---
sidebar: sidebar 
permalink: concepts/licensing.html 
keywords: license, licensing 
summary: Astra Control Center를 사용하여 수행할 수 있는 작업은 라이센스 상태에 따라 어떻게 다르며, Astra Control Center를 사용하는 경우 라이센스 소모에 어떤 영향을 미치는지 알아보십시오. 
---
= 라이센싱
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Astra Control Center는 전체 앱 데이터 관리 기능을 사용하려면 라이센스를 설치해야 합니다. 라이센스 없이 Astra Control Center를 배포하는 경우, 시스템 기능이 제한된다는 경고 메시지가 웹 UI에 표시됩니다.

다음 방법 중 하나를 사용하여 라이센스를 얻습니다.

* link:https://mysupport.netapp.com/site/downloads/evaluation/astra-control-center["Astra Control Center를 평가 중인 경우 평가판 라이센스 파일을 다운로드하십시오"^]. 평가판 라이센스를 사용하면 라이센스를 다운로드한 날짜로부터 90일 동안 Astra Control Center를 사용할 수 있습니다.
* link:https://mysupport.netapp.com/site/["Astra Control Center를 이미 구입한 경우 NetApp 라이센스 파일(NLF)을 생성합니다."^] NetApp Support 사이트에서. 제품을 구입한 후에는 지원 사이트에서 사용하는 일련 번호와 라이센스가 제공됩니다.


ONTAP 스토리지 백엔드에 필요한 라이센스에 대한 자세한 내용은 을 참조하십시오 link:../get-started/requirements.html["지원되는 스토리지 백엔드"].


NOTE: 라이센스 없이 클러스터를 추가하고, 버킷을 추가하고, 스토리지 백엔드를 관리할 수 있습니다.



== 라이선스 소비량의 계산 방법

Astra Control Center에 새 클러스터를 추가하면 클러스터에서 실행 중인 하나 이상의 애플리케이션이 Astra Control Center에 의해 관리되기 전에는 사용된 라이센스에 포함되지 않습니다.

클러스터에서 응용 프로그램 관리를 시작하면 해당 클러스터의 모든 CPU 유닛이 Astra Control Center 라이센스 소모에 포함됩니다.



== 자세한 내용을 확인하십시오

* link:../get-started/setup_overview.html#add-a-license-for-astra-control-center["Astra Control Center를 처음 설정할 때 라이센스를 추가합니다"]
* link:../use/update-licenses.html["기존 라이센스를 업데이트합니다"]

