---
sidebar: sidebar 
permalink: use/define-custom-app.html 
keywords: manage app, custom app, kubernetes, astra control, astra 
summary: 사용자 지정 앱을 생성하면 Kubernetes 클러스터의 요소를 단일 앱으로 그룹화할 수 있습니다. 
---
= 사용자 지정 앱 예제를 정의합니다
:hardbreaks:
:icons: font
:imagesdir: ../media/use/


[role="lead"]
사용자 지정 앱을 생성하면 Kubernetes 클러스터의 요소를 단일 앱으로 그룹화할 수 있습니다.

사용자 지정 앱을 사용하면 다음을 비롯하여 Astra Control 작업에 포함할 항목을 보다 세부적으로 제어할 수 있습니다.

* 복제
* 스냅샷
* 백업
* 보호 정책


대부분의 경우 전체 앱에서 Astra Control의 기능을 사용해야 합니다. 그러나 사용자 지정 앱을 만들어 네임스페이스에서 Kubernetes 개체에 할당하는 레이블을 통해 이러한 기능을 사용할 수도 있습니다.

사용자 지정 앱을 만들려면 앱 페이지로 이동하여 **+정의**를 선택합니다.

사용자 지정 앱 창에는 사용자 지정 앱에서 포함 또는 제외할 리소스가 표시됩니다. 이렇게 하면 사용자 지정 앱을 정의하는 올바른 기준을 선택할 수 있습니다.


NOTE: 맞춤형 앱은 단일 클러스터에서 지정된 네임스페이스 내에서만 생성할 수 있습니다. Astra Control은 사용자 지정 응용 프로그램이 여러 네임스페이스 또는 클러스터를 확장하는 기능을 지원하지 않습니다.

레이블은 식별을 위해 Kubernetes 객체에 할당할 수 있는 키/값 쌍입니다. 레이블을 사용하면 Kubernetes 오브젝트를 더 쉽게 정렬, 구성 및 찾을 수 있습니다. Kubernetes 레이블에 대해 자세히 알아보려면 https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/["Kubernetes 공식 문서를 참조하십시오"^].


WARNING: 이름이 다른 동일한 리소스에 대해 정책을 중복하면 데이터 충돌이 발생할 수 있습니다. 리소스에 대한 사용자 지정 앱을 만드는 경우 다른 정책에 따라 복제되거나 백업되지 않도록 해야 합니다.



== 예: Canary 릴리즈에 대한 별도의 보호 정책

이 예제에서 DevOps 팀은 카나리아 릴리스 배포를 관리합니다. 그들의 클러스터에는 Nginx를 실행하는 3개의 포드가 있습니다. 포드 중 2개는 안정적인 릴리스 전용입니다. 세 번째 포드는 카나리 해제 시 사용합니다.

DevOps 팀의 Kubernetes 관리자가 안정적인 릴리즈 포드에 'duekment=stable'이라는 레이블을 추가합니다. 개발 팀은 카나리 릴리즈 포드에 'deement=canary' 레이블을 추가합니다.

이 팀의 안정적인 릴리즈에는 시간별 스냅샷 및 일일 백업에 대한 요구 사항이 포함됩니다. 카나리아 릴리스는 수명이 길기 때문에 '배포 = 카나리'라고 표시된 모든 것에 대해 공격적이고 단기적인 보호 정책을 만들고자 합니다.

데이터 충돌을 방지하기 위해 관리자는 Canary 릴리스용 응용 프로그램과 안정적 릴리스용 응용 프로그램의 두 가지 사용자 지정 응용 프로그램을 만듭니다. 이렇게 하면 두 Kubernetes 객체 그룹에 대해 백업, 스냅샷 및 클론 작업이 분리됩니다.

.단계
. 팀이 Astra Control에 클러스터를 추가한 후 다음 단계는 사용자 지정 앱을 정의하는 것입니다. 이를 위해 팀은 앱 페이지에서 **+정의** 버튼을 선택합니다.
. 팝업 창이 나타나면 팀은 앱 이름으로 devops-canary-deployment를 설정합니다. 팀은** 클러스터** 드롭다운에서 클러스터를 선택한 다음** 네임스페이스** 드롭다운에서 해당 앱의 네임스페이스를 선택합니다.
. 팀은** Labels** 필드에 duement=canary를 입력하거나 아래 나열된 리소스에서 해당 레이블을 선택할 수 있습니다.
. 카나리아 배포를 위한 사용자 지정 앱을 정의한 후 팀은 안정적인 배포를 위해 프로세스를 반복합니다.


팀이 두 개의 사용자 지정 앱을 모두 만든 후에는 이러한 리소스를 다른 Astra Control 응용 프로그램으로 처리할 수 있습니다. Kubernetes 레이블을 기반으로 각 리소스 그룹에 대해 클론을 생성하고, 백업과 스냅샷을 생성하고, 사용자 지정 보호 정책을 생성할 수 있습니다.
