---
sidebar: sidebar 
permalink: use/manage-local-users-and-roles.html 
keywords: add users, edit users, remove users, delete users, manage roles 
summary: Astra Control Center 시스템에서 사용자 및 역할을 관리합니다. 
---
= 로컬 사용자 및 역할 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control Center 설치 사용자는 Astra Control UI를 사용하여 추가, 제거 및 편집할 수 있습니다. Astra Control UI 또는 를 사용할 수 있습니다 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 를 눌러 사용자를 관리합니다.

LDAP를 사용하여 선택한 사용자에 대한 인증을 수행할 수도 있습니다.



== LDAP를 사용합니다

LDAP는 분산된 디렉터리 정보에 액세스하기 위한 업계 표준 프로토콜이며 엔터프라이즈 인증에 널리 사용되는 프로토콜입니다. Astra Control Center를 LDAP 서버에 연결하여 선택한 Astra Control 사용자에 대한 인증을 수행할 수 있습니다. 이 구성에는 Astra와 LDAP를 통합하고 LDAP 정의에 해당하는 Astra Control 사용자 및 그룹을 정의하는 작업이 포함됩니다. Astra Control API 또는 웹 UI를 사용하여 LDAP 인증과 LDAP 사용자 및 그룹을 구성할 수 있습니다. 자세한 내용은 다음 설명서를 참조하십시오.

* https://docs.netapp.com/us-en/astra-automation/workflows_infra/ldap_prepare.html["Astra Control API를 사용하여 원격 인증 및 사용자를 관리합니다"^]
* link:manage-remote-users-groups.html["Astra Control UI를 사용하여 원격 사용자 및 그룹을 관리합니다"]
* link:manage-remote-authentication.html["Astra Control UI를 사용하여 원격 인증을 관리합니다"]




== 사용자 추가

계정 소유자와 관리자는 Astra Control Center 설치에 사용자를 더 추가할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭을 선택합니다.
. 사용자 추가 * 를 선택합니다.
. 사용자 이름, 이메일 주소 및 임시 암호를 입력합니다.
+
사용자는 처음 로그인할 때 암호를 변경해야 합니다.

. 적절한 시스템 권한이 있는 사용자 역할을 선택합니다.
+
각 역할은 다음과 같은 권한을 제공합니다.

+
** Viewer * 는 리소스를 볼 수 있습니다.
** 구성원 * 은 뷰어 역할 권한을 가지며 앱 및 클러스터를 관리하고, 앱을 관리하고, 스냅샷 및 백업을 삭제할 수 있습니다.
** Admin * 은 구성원 역할 권한을 가지며 소유자를 제외한 다른 사용자를 추가 및 제거할 수 있습니다.
** 소유자 * 는 관리자 역할 권한을 가지며 모든 사용자 계정을 추가 및 제거할 수 있습니다.


. 멤버 또는 뷰어 역할이 있는 사용자에게 제약 조건을 추가하려면 * 제약 조건으로 역할 제한 * 확인란을 활성화합니다.
+
제약 조건 추가에 대한 자세한 내용은 을 참조하십시오 link:manage-local-users-and-roles.html["로컬 사용자 및 역할 관리"].

. 추가 * 를 선택합니다.




== 암호 관리

Astra Control Center에서 사용자 계정의 암호를 관리할 수 있습니다.



=== 암호를 변경합니다

언제든지 사용자 계정의 암호를 변경할 수 있습니다.

.단계
. 화면 오른쪽 상단에서 사용자 아이콘을 선택합니다.
. 프로파일 * 을 선택합니다.
. 작업 * 열의 옵션 메뉴에서 * 암호 변경 * 을 선택합니다.
. 암호 요구 사항에 맞는 암호를 입력합니다.
. 암호를 다시 입력하여 확인합니다.
. 암호 변경 * 을 선택합니다.




=== 다른 사용자의 암호를 재설정합니다

계정에 관리자 또는 소유자 역할 권한이 있는 경우 다른 사용자 계정과 사용자의 암호를 재설정할 수 있습니다. 암호를 재설정할 때 사용자가 로그인할 때 변경해야 하는 임시 암호를 할당합니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 작업 * 드롭다운 목록을 선택합니다.
. 암호 재설정 * 을 선택합니다.
. 암호 요구 사항에 맞는 임시 암호를 입력합니다.
. 암호를 다시 입력하여 확인합니다.
+

NOTE: 다음에 사용자가 로그인할 때 암호를 변경하라는 메시지가 표시됩니다.

. 비밀번호 재설정 * 을 선택합니다.




== 사용자를 제거합니다

소유자 또는 관리자 역할을 가진 사용자는 언제든지 계정에서 다른 사용자를 제거할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭에서 제거할 각 사용자의 행에서 확인란을 선택합니다.
. Actions * 열의 Options 메뉴에서 * Remove user/s * 를 선택합니다.
. 메시지가 표시되면 "remove(제거)"라는 단어를 입력한 다음 * Yes, Remove User(예, 사용자 제거) * 를 선택하여 삭제를 확인합니다.


.결과
Astra Control Center는 계정에서 사용자를 제거합니다.



== 역할을 관리합니다

네임스페이스 제약 조건을 추가하고 이러한 제약 조건에 대한 사용자 역할을 제한하여 역할을 관리할 수 있습니다. 이렇게 하면 조직 내의 리소스에 대한 액세스를 제어할 수 있습니다. Astra Control UI 또는 를 사용할 수 있습니다 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 역할을 관리합니다.



=== 역할에 네임스페이스 제약 조건을 추가합니다

관리자 또는 소유자 사용자는 구성원 또는 뷰어 역할에 네임스페이스 제약 조건을 추가할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭을 선택합니다.
. Actions * 열에서 Member 또는 Viewer 역할을 가진 사용자의 메뉴 버튼을 선택합니다.
. 역할 편집 * 을 선택합니다.
. 제약 조건으로 역할 제한 * 확인란을 활성화합니다.
+
이 확인란은 구성원 또는 뷰어 역할에만 사용할 수 있습니다. 역할 * 드롭다운 목록에서 다른 역할을 선택할 수 있습니다.

. 구속 조건 추가 * 를 선택합니다.
+
네임스페이스 또는 네임스페이스 레이블별로 사용 가능한 제약 조건 목록을 볼 수 있습니다.

. 네임스페이스 구성 방법에 따라 * 제약 조건 유형 * 드롭다운 목록에서 * Kubernetes 네임스페이스 * 또는 * Kubernetes 네임스페이스 레이블 * 을 선택합니다.
. 목록에서 하나 이상의 네임스페이스 또는 레이블을 선택하여 해당 네임스페이스로 역할을 제한하는 제약 조건을 구성합니다.
. Confirm * 을 선택합니다.
+
역할 편집 * 페이지에는 이 역할에 대해 선택한 제약 조건 목록이 표시됩니다.

. Confirm * 을 선택합니다.
+
계정 * 페이지의 * 역할 * 열에서 구성원 또는 뷰어 역할에 대한 제약 조건을 볼 수 있습니다.




NOTE: 역할에 대한 제약 조건을 설정하고 제약 조건을 추가하지 않고 * 확인 * 을 선택하면 역할이 전체 제한 사항으로 간주됩니다(역할에 네임스페이스가 할당된 리소스에 대한 액세스가 거부됨).



=== 역할에서 네임스페이스 제약 조건을 제거합니다

관리자 또는 소유자 사용자는 역할에서 네임스페이스 제약 조건을 제거할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭을 선택합니다.
. Actions * 열에서 활성 제약 조건이 있는 Member 또는 Viewer 역할을 가진 사용자의 메뉴 버튼을 선택합니다.
. 역할 편집 * 을 선택합니다.
+
역할 편집 * 대화 상자에 해당 역할에 대한 활성 제약 조건이 표시됩니다.

. 제거할 구속 조건의 오른쪽에 있는 * X * 를 선택합니다.
. Confirm * 을 선택합니다.




== 를 참조하십시오

* link:../concepts/user-roles-namespaces.html["사용자 역할 및 네임스페이스"]

