---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: how to set up object storage in astra, how to set up astra buckets, s3, astra, setting up astra control, how to set up astra control center, kubernetes 
summary: 클러스터 간에 애플리케이션을 복제하려는 경우 애플리케이션 및 영구 스토리지를 백업하려는 경우 오브젝트 저장소 버킷 공급자를 추가하는 것이 중요합니다. 
---
= 버킷을 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


애플리케이션 및 영구 스토리지를 백업하려는 경우나 클러스터 간에 애플리케이션을 클론 복제하려는 경우에는 오브젝트 저장소 버킷 공급자가 필수적입니다. Astra Control Center를 사용하여 객체 저장소 공급자를 오프라인 클러스터, 앱의 백업 대상으로 추가합니다.

애플리케이션 구성과 영구 스토리지를 동일한 클러스터에 클론 복제할 경우 버킷이 필요하지 않습니다.

다음 버킷 공급자 중 하나를 사용하십시오.

* NetApp ONTAP S3
* NetApp StorageGRID S3
* 일반 S3



NOTE: Astra Control Center는 Amazon S3를 일반 S3 버킷 공급자로 지원하지만, Astra Control Center는 Amazon의 S3 지원을 주장하는 모든 오브젝트 저장소 공급업체를 지원하지 않을 수 있습니다.

버킷은 삭제할 수 없지만 편집할 수는 있습니다.

버킷은 다음 상태 중 하나일 수 있습니다.

* 보류 중: 버킷이 검색되도록 예약되었습니다.
* 사용 가능: 버킷을 사용할 수 있습니다.
* 제거: 현재 버킷에 접근할 수 없습니다.


Astra Control API를 사용하여 버킷을 관리하는 방법에 대한 지침은 을 참조하십시오 link:https://docs.netapp.com/us-en/astra-automation/["Astra 자동화 및 API 정보"^].

버킷 관리와 관련된 다음 작업을 수행할 수 있습니다.

* link:../get-started/setup_overview.html#add-a-bucket["버킷을 추가합니다"]
* <<Edit a bucket>>



NOTE: Astra Control Center의 S3 버킷은 가용 용량을 보고하지 않습니다. Astra Control Center에서 관리하는 앱을 백업 또는 클론 생성하기 전에 ONTAP 또는 StorageGRID 관리 시스템에서 버킷 정보를 확인하십시오.



== 자격 증명을 제거합니다

Astra Control API를 사용하여 언제든지 계정에서 S3 자격 증명을 제거합니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API를 사용합니다"^].


TIP: Astra Control에 추가하는 첫 번째 자격 증명 세트는 항상 사용 중입니다. Astra Control은 자격 증명을 사용하여 백업 버킷을 인증하기 때문입니다. 이러한 자격 증명을 제거하지 않는 것이 좋습니다.



== 버킷을 편집합니다

버킷의 액세스 자격 증명 정보를 변경하고 선택한 버킷이 기본 버킷인지 여부를 변경할 수 있습니다.


NOTE: 버킷을 추가할 때 올바른 버킷 공급자를 선택하고 해당 공급자에 적합한 자격 증명을 제공합니다. 예를 들어, UI에서 NetApp ONTAP S3를 유형으로 받아들이고 StorageGRID 자격 증명을 받아들이지만, 이 버킷을 사용한 이후의 모든 애플리케이션 백업 및 복원이 실패합니다. 를 참조하십시오 link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures["릴리즈 노트"].

.단계
. 왼쪽 탐색에서 * Bucket * 을 선택합니다.
. 작업 메뉴에서 * 편집 * 을 선택합니다.
. 버킷 유형 이외의 모든 정보를 변경합니다.
+

TIP: 버킷 유형을 수정할 수 없습니다.

. Update * 를 선택합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API를 사용합니다"^]

