---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: Astra Control Center 시스템에 사용자를 추가하고 더 이상 시스템에 액세스할 수 없는 사용자를 제거합니다. 
---
= 사용자 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Astra Control Center 설치 사용자를 Astra Control UI를 사용하여 초대, 추가, 제거 및 편집할 수 있습니다. Astra Control UI 또는 를 사용할 수 있습니다 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 를 눌러 사용자를 관리합니다.



== 사용자를 초대합니다

계정 소유자와 관리자는 새 사용자를 Astra Control Center에 초대할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭을 선택합니다.
. 사용자 초대 * 를 선택합니다.
. 사용자의 이름과 이메일 주소를 입력합니다.
. 적절한 시스템 권한이 있는 사용자 역할을 선택합니다.
+
각 역할은 다음과 같은 권한을 제공합니다.

+
** Viewer * 는 리소스를 볼 수 있습니다.
** 구성원 * 은 뷰어 역할 권한을 가지며 앱 및 클러스터를 관리하고, 앱을 관리하고, 스냅샷 및 백업을 삭제할 수 있습니다.
** Admin * 은 구성원 역할 권한을 가지며 소유자를 제외한 다른 사용자를 추가 및 제거할 수 있습니다.
** 소유자 * 는 관리자 역할 권한을 가지며 모든 사용자 계정을 추가 및 제거할 수 있습니다.


. 멤버 또는 뷰어 역할이 있는 사용자에게 제약 조건을 추가하려면 * 제약 조건으로 역할 제한 * 확인란을 활성화합니다.
+
제약 조건 추가에 대한 자세한 내용은 을 참조하십시오 link:manage-roles.html["역할을 관리합니다"].

. 사용자 초대 * 를 선택합니다.
+
사용자에게 Astra Control Center에 초대되었음을 알리는 이메일이 전송됩니다. 이 이메일에는 임시 암호가 포함되어 있으며, 이 암호는 처음 로그인할 때 변경해야 합니다.





== 사용자 추가

계정 소유자와 관리자는 Astra Control Center 설치에 사용자를 더 추가할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭을 선택합니다.
. 사용자 추가 * 를 선택합니다.
. 사용자 이름, 이메일 주소 및 임시 암호를 입력합니다.
+
사용자는 처음 로그인할 때 암호를 변경해야 합니다.

. 적절한 시스템 권한이 있는 사용자 역할을 선택합니다.
+
각 역할은 다음과 같은 권한을 제공합니다.

+
** Viewer * 는 리소스를 볼 수 있습니다.
** 구성원 * 은 뷰어 역할 권한을 가지며 앱 및 클러스터를 관리하고, 앱을 관리하고, 스냅샷 및 백업을 삭제할 수 있습니다.
** Admin * 은 구성원 역할 권한을 가지며 소유자를 제외한 다른 사용자를 추가 및 제거할 수 있습니다.
** 소유자 * 는 관리자 역할 권한을 가지며 모든 사용자 계정을 추가 및 제거할 수 있습니다.


. 멤버 또는 뷰어 역할이 있는 사용자에게 제약 조건을 추가하려면 * 제약 조건으로 역할 제한 * 확인란을 활성화합니다.
+
제약 조건 추가에 대한 자세한 내용은 을 참조하십시오 link:manage-roles.html["역할을 관리합니다"].

. 추가 * 를 선택합니다.




== 암호 관리

Astra Control Center에서 사용자 계정의 암호를 관리할 수 있습니다.



=== 암호를 변경합니다

언제든지 사용자 계정의 암호를 변경할 수 있습니다.

.단계
. 화면 오른쪽 상단에서 사용자 아이콘을 선택합니다.
. 프로파일 * 을 선택합니다.
. 작업 * 열의 옵션 메뉴에서 * 암호 변경 * 을 선택합니다.
. 암호 요구 사항에 맞는 암호를 입력합니다.
. 암호를 다시 입력하여 확인합니다.
. 암호 변경 * 을 선택합니다.




=== 다른 사용자의 암호를 재설정합니다

계정에 관리자 또는 소유자 역할 권한이 있는 경우 다른 사용자 계정과 사용자의 암호를 재설정할 수 있습니다. 암호를 재설정할 때 사용자가 로그인할 때 변경해야 하는 임시 암호를 할당합니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 작업 * 드롭다운 목록을 선택합니다.
. 암호 재설정 * 을 선택합니다.
. 암호 요구 사항에 맞는 임시 암호를 입력합니다.
. 암호를 다시 입력하여 확인합니다.
+

NOTE: 다음에 사용자가 로그인할 때 암호를 변경하라는 메시지가 표시됩니다.

. 비밀번호 재설정 * 을 선택합니다.




== 사용자의 역할을 변경합니다

소유자 역할을 가진 사용자는 모든 사용자의 역할을 변경할 수 있지만 관리자 역할을 가진 사용자는 관리자, 구성원 또는 뷰어 역할을 가진 사용자의 역할을 변경할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 작업 * 드롭다운 목록을 선택합니다.
. 역할 편집 * 을 선택합니다.
. 새 역할을 선택합니다.
. 역할에 제약 조건을 적용하려면 * 제약 조건으로 역할 제한 * 확인란을 선택하고 목록에서 제약 조건을 선택합니다.
+
구속조건이 없으면 구속조건을 추가할 수 있습니다. 자세한 내용은 을 참조하십시오 link:manage-roles.html["역할을 관리합니다"].

. Confirm * 을 선택합니다.


Astra Control Center는 선택한 새 역할에 따라 사용자의 권한을 업데이트합니다.



== 사용자를 제거합니다

소유자 또는 관리자 역할을 가진 사용자는 언제든지 계정에서 다른 사용자를 제거할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 사용자 * 탭에서 제거할 각 사용자의 행에서 확인란을 선택합니다.
. Actions * 열의 Options 메뉴에서 * Remove user/s * 를 선택합니다.
. 메시지가 표시되면 "remove(제거)"라는 단어를 입력한 다음 * Yes, Remove User(예, 사용자 제거) * 를 선택하여 삭제를 확인합니다.


Astra Control Center는 계정에서 사용자를 제거합니다.
