---
sidebar: sidebar 
permalink: use/manage-remote-users-groups.html 
keywords: import, import users, search, search users, groups, import groups 
summary: Astra Control Center 시스템에서 원격 LDAP 사용자 및 그룹을 관리합니다. 
---
= 원격 사용자 및 그룹 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control 시스템에서 LDAP 인증을 활성화한 경우 LDAP 사용자 및 그룹을 검색하여 승인된 시스템 사용자에게 포함시킬 수 있습니다.



== 원격 사용자를 추가합니다

계정 소유자와 관리자는 Astra Control에 원격 사용자를 추가할 수 있습니다.


NOTE: 동일한 이메일 주소를 가진 로컬 사용자가 이미 시스템에 있는 경우 원격 사용자를 추가할 수 없습니다. 사용자를 원격 사용자로 추가하려면 먼저 시스템에서 로컬 사용자를 삭제합니다.


IMPORTANT: Astra Control Center는 LDAP "mail" 속성의 이메일 주소를 사용하여 원격 사용자를 검색하고 추적합니다. 이 속성은 디렉터리의 선택적 필드이거나 빈 필드일 수 있습니다. Astra Control Center에 표시하고자 하는 원격 사용자의 경우 이 필드에 이메일 주소가 있어야 합니다. 이 이메일 주소는 인증을 위해 Astra Control Center의 사용자 이름으로 사용됩니다.

.단계
. 계정 * 영역으로 이동합니다.
. 사용자 및 그룹 * 탭을 선택합니다.
. 페이지 맨 오른쪽에서 * 원격 사용자 * 를 선택합니다.
. 추가 * 를 선택합니다.
. 선택적으로 * Filter by email * 필드에 사용자의 이메일 주소를 입력하여 LDAP 사용자를 검색합니다.
. 목록에서 한 명 이상의 사용자를 선택합니다.
. 사용자에게 역할을 할당합니다.
+

NOTE: 사용자와 사용자 그룹에 서로 다른 역할을 할당하면 더 많은 권한을 허용하는 역할이 우선합니다.

. 필요한 경우 이 사용자에게 하나 이상의 네임스페이스 제약 조건을 할당하고 * 제약 조건으로 역할 제한 * 을 선택하여 해당 제약 조건을 적용합니다. 제약 조건 추가 * 를 선택하여 새 네임스페이스 제약 조건을 추가할 수 있습니다.
+

NOTE: 사용자가 LDAP 그룹 구성원 자격을 통해 여러 역할을 할당하면 가장 허용 가능한 역할의 제약 조건만 적용됩니다. 예를 들어, 로컬 뷰어 역할을 가진 사용자가 멤버 역할에 바인딩된 세 개의 그룹에 참여하는 경우 멤버 역할의 제약 조건의 합계가 적용되고 뷰어 역할의 모든 제약 조건은 무시됩니다.

. 추가 * 를 선택합니다.


.결과
새 사용자가 원격 사용자 목록에 나타납니다. 이 목록에서 사용자의 활성 제약 조건을 확인하고 * Actions * 메뉴에서 사용자를 관리할 수 있습니다.



== 원격 그룹을 추가합니다

한 번에 많은 원격 사용자를 추가하려면 계정 소유자와 관리자가 Astra Control에 원격 그룹을 추가할 수 있습니다. 원격 그룹을 추가하면 해당 그룹의 모든 원격 사용자가 Astra Control에 추가되고 동일한 역할을 상속합니다.

.단계
. 계정 * 영역으로 이동합니다.
. 사용자 및 그룹 * 탭을 선택합니다.
. 페이지 맨 오른쪽에서 * 원격 그룹 * 을 선택합니다.
. 추가 * 를 선택합니다.
+
이 창에서는 Astra Control이 디렉토리에서 검색한 LDAP 그룹의 공통 이름과 고유 이름 목록을 볼 수 있습니다.

. 선택적으로 * Filter by common name * 필드에 그룹의 공통 이름을 입력하여 LDAP 그룹을 검색합니다.
. 목록에서 그룹을 하나 이상 선택합니다.
. 그룹에 역할을 할당합니다.
+

NOTE: 선택한 역할은 이 그룹의 모든 사용자에게 할당됩니다. 사용자와 사용자 그룹에 서로 다른 역할을 할당하면 더 많은 권한을 허용하는 역할이 우선합니다.

. 필요한 경우 이 그룹에 하나 이상의 네임스페이스 제약 조건을 할당하고 * 제약 조건으로 역할 제한 * 을 선택하여 해당 제약 조건을 적용합니다. 제약 조건 추가 * 를 선택하여 새 네임스페이스 제약 조건을 추가할 수 있습니다.
+

NOTE: 사용자가 LDAP 그룹 구성원 자격을 통해 여러 역할을 할당하면 가장 허용 가능한 역할의 제약 조건만 적용됩니다. 예를 들어, 로컬 뷰어 역할을 가진 사용자가 멤버 역할에 바인딩된 세 개의 그룹에 참여하는 경우 멤버 역할의 제약 조건의 합계가 적용되고 뷰어 역할의 모든 제약 조건은 무시됩니다.

. 추가 * 를 선택합니다.


.결과
새 그룹이 원격 그룹 목록에 나타나고 이 그룹의 모든 원격 사용자가 원격 사용자 목록에 나타납니다. 이 목록에서 그룹에 대한 세부 정보를 볼 수 있을 뿐 아니라 * Actions * 메뉴에서 그룹을 관리할 수 있습니다.
