---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: 언제든지 계정에서 클라우드 공급자 자격 증명을 추가 및 제거할 수 있습니다. Astra는 이러한 자격 증명을 사용하여 사용자를 대신하여 리소스를 제공합니다. 
---
= 자격 증명을 추가 및 제거합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
ONTAP S3, OpenShift로 관리되는 Kubernetes 클러스터, 또는 관리되지 않는 Kubernetes 클러스터와 같은 로컬 프라이빗 클라우드 공급자의 자격 증명을 언제든지 계정에서 추가 및 제거할 수 있습니다. Astra Control Center는 이러한 자격 증명을 사용하여 Kubernetes 클러스터 및 클러스터의 앱을 검색하고 대신 리소스를 프로비저닝합니다.

Astra Control Center의 모든 사용자는 동일한 자격 증명 세트를 공유합니다.



== 자격 증명을 추가합니다

클러스터를 관리할 때 Astra Control Center에 자격 증명을 추가할 수 있습니다. 새 클러스터를 추가하여 자격 증명을 추가하려면 을 참조하십시오 link:../get-started/setup_overview.html#add-cluster["Kubernetes 클러스터 추가"].


IMPORTANT: 고유한 "kubecononfig" 파일을 만들 경우 해당 파일에 * 하나의 * 컨텍스트 요소만 정의해야 합니다. 을 참조하십시오 https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Kubernetes 문서"^] kubecononfig 파일을 만드는 방법에 대한 자세한 내용은



== 자격 증명을 제거합니다

언제든지 계정에서 자격 증명을 제거합니다. 자격 증명은 이후에 제거해야 합니다 link:unmanage.html["연결된 모든 클러스터의 관리를 취소합니다"].


NOTE: Astra Control Center에 추가하는 첫 번째 자격 증명 세트는 항상 사용 중입니다. Astra Control Center는 자격 증명을 사용하여 백업 버킷에 인증하기 때문입니다. 이러한 자격 증명을 제거하지 않는 것이 좋습니다.

.단계
. 계정 * 을 선택합니다.
. 자격 증명 * 탭을 선택합니다.
. 제거할 자격 증명에 대한 * 상태 * 열의 옵션 메뉴를 선택합니다.
. 제거 * 를 선택합니다.
. 삭제를 확인하려면 "remove(제거)"라는 단어를 입력한 다음 * Yes(예), Remove Credential(자격 증명 제거) * 을 선택합니다.


Astra Control Center는 계정에서 자격 증명을 제거합니다.
