---
sidebar: sidebar 
permalink: use/manage-remote-authentication.html 
keywords: enable ldap authentication, disable, ldap, authentication, configure, manage 
summary: Astra Control 시스템에서 LDAP 인증을 관리합니다. 
---
= 원격 인증을 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
LDAP는 분산된 디렉터리 정보에 액세스하기 위한 업계 표준 프로토콜이며 엔터프라이즈 인증에 널리 사용되는 프로토콜입니다. Astra Control Center를 LDAP 서버에 연결하여 선택한 Astra Control 사용자에 대한 인증을 수행할 수 있습니다.

이 구성에는 Astra와 LDAP를 통합하고 LDAP 정의에 해당하는 Astra Control 사용자 및 그룹을 정의하는 작업이 포함됩니다. Astra Control API 또는 웹 UI를 사용하여 LDAP 인증과 LDAP 사용자 및 그룹을 구성할 수 있습니다.


IMPORTANT: Astra Control Center는 LDAP "mail" 속성의 이메일 주소를 사용하여 원격 사용자를 검색하고 추적합니다. 이 속성은 디렉터리의 선택적 필드이거나 빈 필드일 수 있습니다. Astra Control Center에 표시하고자 하는 원격 사용자의 경우 이 필드에 이메일 주소가 있어야 합니다. 이 이메일 주소는 인증을 위해 Astra Control Center의 사용자 이름으로 사용됩니다.



== LDAPS 인증을 위한 인증서를 추가합니다

LDAPS 연결을 사용할 때 Astra Control Center가 LDAP 서버를 인증할 수 있도록 LDAP 서버에 대한 개인 TLS 인증서를 추가합니다. 이 작업은 한 번만 수행하거나 설치한 인증서가 만료되면 수행해야 합니다.

.단계
. 계정 * 으로 이동합니다.
. 인증서 * 탭을 선택합니다.
. 추가 * 를 선택합니다.
. 를 업로드하거나 `.pem` 클립보드에서 파일의 내용을 파일 또는 붙여 넣습니다.
. 신뢰할 수 있는 * 확인란을 선택합니다.
. 인증서 추가 * 를 선택합니다.




== 원격 인증을 사용합니다

LDAP 인증을 설정하고 Astra Control과 원격 LDAP 서버 간의 연결을 구성할 수 있습니다.

.시작하기 전에
LDAPS를 사용하려는 경우 Astra Control Center에서 LDAP 서버를 인증할 수 있도록 LDAP 서버의 개인 TLS 인증서가 Astra Control Center에 설치되어 있는지 확인합니다. 을 참조하십시오 <<LDAPS 인증을 위한 인증서를 추가합니다>> 를 참조하십시오.

.단계
. 계정 > 연결 * 으로 이동합니다.
. Remote Authentication* 창에서 구성 메뉴를 선택합니다.
. Connect * 를 선택합니다.
. 서버 IP 주소, 포트 및 기본 설정 연결 프로토콜(LDAP 또는 LDAPS)을 입력합니다.
+

NOTE: 가장 좋은 방법은 LDAP 서버와 연결할 때 LDAPS를 사용하는 것입니다. LDAPS에 연결하기 전에 Astra Control Center에 LDAP 서버의 개인 TLS 인증서를 설치해야 합니다.

. 서비스 계정 자격 증명을 이메일 형식(administrator@example.com 입력합니다. Astra Control은 LDAP 서버에 연결할 때 이러한 자격 증명을 사용합니다.
. 사용자 일치 * 섹션에서 기본 DN과 LDAP 서버에서 사용자 정보를 검색할 때 사용할 적절한 사용자 검색 필터를 입력합니다.
. 그룹 일치 * 섹션에서 그룹 검색 기준 DN과 적절한 사용자 지정 그룹 검색 필터를 입력합니다.
+

NOTE: 올바른 기본 DN(고유 이름)과 * 사용자 일치 * 및 * 그룹 일치 * 에 대한 적절한 검색 필터를 사용해야 합니다. 기본 DN은 Astra Control에 검색을 시작할 디렉토리 트리의 수준을 알리고 검색 필터는 디렉토리 트리 Astra Control의 검색 부분을 제한합니다.

. 제출 * 을 선택합니다.


.결과
원격 인증 * 창 상태는 * Pending * 으로 이동한 다음 LDAP 서버 연결이 설정되면 * Connected * 로 이동합니다.



== 원격 인증을 비활성화합니다

LDAP 서버에 대한 활성 연결을 일시적으로 해제할 수 있습니다.


NOTE: LDAP 서버에 대한 연결을 비활성화하면 모든 설정이 저장되고 해당 LDAP 서버에서 Astra Control에 추가된 모든 원격 사용자 및 그룹은 유지됩니다. 언제든지 이 LDAP 서버에 다시 연결할 수 있습니다.

.단계
. 계정 > 연결 * 으로 이동합니다.
. Remote Authentication* 창에서 구성 메뉴를 선택합니다.
. 비활성화 * 를 선택합니다.


.결과
원격 인증* 창 상태가 * 사용 안 함 * 으로 이동합니다. 모든 원격 인증 설정, 원격 사용자 및 원격 그룹이 보존되며 언제든지 연결을 다시 활성화할 수 있습니다.



== 원격 인증 설정을 편집합니다

LDAP 서버에 대한 연결을 해제했거나 * 원격 인증 * 창이 "연결 오류" 상태인 경우 구성 설정을 편집할 수 있습니다.


NOTE: 원격 인증* 창이 "사용 안 함" 상태이면 LDAP 서버 URL 또는 IP 주소를 편집할 수 없습니다. 다음 작업을 수행해야 합니다 <<원격 인증 연결을 끊습니다>> 먼저,

.단계
. 계정 > 연결 * 으로 이동합니다.
. Remote Authentication* 창에서 구성 메뉴를 선택합니다.
. 편집 * 을 선택합니다.
. 필요한 내용을 변경하고 * Edit * 를 선택합니다.




== 원격 인증 연결을 끊습니다

LDAP 서버에서 연결을 끊고 Astra Control에서 구성 설정을 제거할 수 있습니다.


CAUTION: LDAP 서버에서 연결을 끊으면 해당 LDAP 서버에 대한 모든 구성 설정이 Astra Control에서 제거되고 해당 LDAP 서버에서 추가된 모든 원격 사용자 및 그룹이 제거됩니다.

.단계
. 계정 > 연결 * 으로 이동합니다.
. Remote Authentication* 창에서 구성 메뉴를 선택합니다.
. Disconnect * 를 선택합니다.


.결과
원격 인증 * 창 상태가 * 연결 끊김 * 으로 이동합니다. 원격 인증 설정, 원격 사용자 및 원격 그룹은 Astra Control에서 제거됩니다.
