---
sidebar: sidebar 
permalink: use/manage-packages-acc.html 
keywords: manage package, packages, install 
summary: Astra Control Center에 패키지를 업로드하고 설치할 수 있습니다. 
---
= 소프트웨어 패키지를 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


NetApp은 NetApp Support 사이트에서 다운로드할 수 있는 소프트웨어 패키지가 포함된 Astra Control Center에 대한 추가 기능을 제공합니다. Docker 및 아티팩트 저장소를 연결한 후 패키지를 업로드 및 가져와 Astra Control Center에 이 기능을 추가할 수 있습니다. CLI 또는 Astra Control Center 웹 UI를 사용하여 소프트웨어 패키지를 관리할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* Astra Control Center가 설치된 Kubernetes 클러스터
* 소프트웨어 패키지 이미지를 보관할 연결된 Docker 이미지 리포지토리입니다. 자세한 내용은 을 참조하십시오 link:manage-connections.html["리포지토리 연결을 관리합니다"].
* 소프트웨어 패키지 바이너리 및 아티팩트를 보관하는 연결된 아티팩트 리포지토리입니다. 자세한 내용은 을 참조하십시오 link:manage-connections.html["리포지토리 연결을 관리합니다"].
* NetApp Support 사이트의 소프트웨어 패키지입니다




== 소프트웨어 패키지 이미지를 리포지토리에 업로드합니다

Astra Control Center는 연결된 저장소의 패키지 이미지 및 아티팩트를 참조합니다. CLI를 사용하여 이미지 및 아티팩트를 리포지토리에 업로드할 수 있습니다.

.단계
. NetApp Support 사이트에서 소프트웨어 패키지를 다운로드한 다음 kubbctl 유틸리티가 설치된 시스템에 저장합니다.
. 압축된 패키지 파일의 압축을 풀고 디렉토리를 Astra Control 번들 파일 위치로 변경합니다(예: acc.manifest.bundle.YAML).
. 패키지 이미지를 Docker 저장소로 푸시합니다. 다음 대체 작업을 수행합니다.
+
** Bundle_file을 Astra Control 번들 파일의 이름으로 바꿉니다.
** my_registry를 Docker 리포지토리의 URL로 바꿉니다.
** my_registry_user와 my_registry_password를 리포지터리의 자격 증명으로 교체합니다.
+
[listing]
----
kubectl astra packages push-images -m BUNDLE_FILE -r MY_REGISTRY -u MY_REGISTRY_USER -p MY_REGISTRY_PASSWORD
----


. 패키지에 아티팩트가 있는 경우 아티팩트를 아티팩트 저장소로 복사합니다. bundle_file을 Astra Control 번들 파일의 이름으로 바꾸고 network_location을 네트워크 위치로 교체하여 다음 위치에 아티팩트 파일을 복사합니다.
+
[listing]
----
kubectl astra packages copy-artifacts -m BUNDLE_FILE -n NETWORK_LOCATION
----




== 소프트웨어 패키지를 추가합니다

Astra Control Center 번들 파일을 사용하여 소프트웨어 패키지를 가져올 수 있습니다. 이렇게 하면 패키지가 설치되고 Astra Control Center에서 소프트웨어를 사용할 수 있습니다.



=== Astra Control 웹 UI를 사용하여 소프트웨어 패키지를 추가합니다

Astra Control Center 웹 UI를 사용하여 연결된 저장소에 업로드된 소프트웨어 패키지를 추가할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 패키지 * 탭을 선택합니다.
. 추가 * 버튼을 선택합니다.
. 파일 선택 대화 상자에서 업로드 아이콘을 선택합니다.
. 업로드할 Astra Control 번들 파일(예: .YAML)을 선택합니다.
. 추가 * 를 선택합니다.


번들 파일이 유효하고 패키지 이미지 및 아티팩트가 연결된 저장소에 있으면 패키지가 Astra Control Center에 추가됩니다. 상태 * 열의 상태가 * 사용 가능 * 으로 변경되면 패키지를 사용할 수 있습니다. 패키지 상태 위로 마우스를 가져가면 추가 정보를 볼 수 있습니다.


NOTE: 리포지토리에 패키지에 대한 하나 이상의 이미지 또는 아티팩트가 없으면 해당 패키지에 대한 오류 메시지가 나타납니다.



=== CLI를 사용하여 소프트웨어 패키지를 추가합니다

CLI를 사용하여 연결된 리포지토리에 업로드한 소프트웨어 패키지를 가져올 수 있습니다. 이를 위해서는 먼저 Astra Control Center 계정 ID와 API 토큰을 기록해야 합니다.

.단계
. 웹 브라우저를 사용하여 Astra Control Center 웹 UI에 로그인합니다.
. 대시보드에서 오른쪽 상단의 사용자 아이콘을 선택합니다.
. API 액세스 * 를 선택합니다.
. 화면 위쪽에 있는 계정 ID를 확인합니다.
. API 토큰 생성 * 을 선택합니다.
. 결과 대화 상자에서 * API 토큰 생성 * 을 선택합니다.
. 결과 토큰을 기록하고 * Close * 를 선택합니다. CLI에서 압축을 푼 패키지 내용물의 .YAML 번들 파일 위치로 디렉터리를 변경합니다.
. 번들 파일을 사용하여 패키지를 가져오고 다음 대체 항목을 만듭니다.
+
** Bundle_file을 Astra Control 번들 파일의 이름으로 바꿉니다.
** 서버를 Astra Control 인스턴스의 DNS 이름으로 바꿉니다.
** account_ID 및 토큰을 이전에 기록한 계정 ID 및 API 토큰으로 교체합니다.
+
[listing]
----
kubectl astra packages import -m BUNDLE_FILE -u SERVER -a ACCOUNT_ID -k TOKEN
----




번들 파일이 유효하고 패키지 이미지 및 아티팩트가 연결된 저장소에 있으면 패키지가 Astra Control Center에 추가됩니다.


NOTE: 리포지토리에 패키지에 대한 하나 이상의 이미지 또는 아티팩트가 없으면 해당 패키지에 대한 오류 메시지가 나타납니다.



== 소프트웨어 패키지를 제거합니다

Astra Control Center 웹 UI를 사용하여 이전에 Astra Control Center에서 가져온 소프트웨어 패키지를 제거할 수 있습니다.

.단계
. 계정 관리 * 탐색 영역에서 * 계정 * 을 선택합니다.
. 패키지 * 탭을 선택합니다.
+
이 페이지에서는 설치된 패키지 목록과 해당 상태를 확인할 수 있습니다.

. 패키지의 * Actions * 열에서 Actions 메뉴를 엽니다.
. 삭제 * 를 선택합니다.


패키지는 Astra Control Center에서 삭제되지만 패키지의 이미지 및 아티팩트는 저장소에 남아 있습니다.

[discrete]
== 자세한 내용을 확인하십시오

* link:manage-connections.html["리포지토리 연결을 관리합니다"]

