---
sidebar: sidebar 
permalink: use/replicate_snapmirror.html 
keywords: replicate, replication, disaster, recovery 
summary: Astra는 스냅샷 또는 백업에서 애플리케이션 구성과 영구 스토리지를 복원할 수 있습니다. 영구 스토리지 백업은 오브젝트 저장소에서 전송되므로 기존 백업에서 복원하면 가장 빠르게 완료됩니다. 
---
= SnapMirror 기술을 사용하여 원격 시스템에 애플리케이션을 복제합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control을 사용하면 NetApp SnapMirror 기술의 비동기식 복제 기능을 사용하여 낮은 RPO(복구 시점 목표) 및 낮은 RTO(복구 시간 목표)로 애플리케이션에 대한 비즈니스 연속성을 구축할 수 있습니다. 이 기능을 구성하면 애플리케이션에서 클러스터 간에 데이터 및 애플리케이션 변경사항을 복제할 수 있습니다.

백업/복구와 복제를 비교하려면 을 참조하십시오 link:../concepts/data-protection.html["데이터 보호 개념"].

다음과 같은 사내 전용, 하이브리드 및 멀티 클라우드 시나리오와 같은 다양한 시나리오에서 앱을 복제할 수 있습니다.

* 사내 사이트 A에서 사내 사이트 B로
* Cloud Volumes ONTAP를 사용하여 사내에서 클라우드로 전환
* Cloud Volumes ONTAP를 사용하는 클라우드를 사내에서 운영
* Cloud Volumes ONTAP를 사용하는 클라우드(동일한 클라우드 공급자 내의 서로 다른 지역 또는 다른 클라우드 공급자 간)


Astra Control은 사내 클러스터, 사내 클러스터, 클라우드(Cloud Volumes ONTAP 사용) 또는 클라우드 간(Cloud Volumes ONTAP에서 Cloud Volumes ONTAP로) 애플리케이션을 복제할 수 있습니다.


NOTE: 다른 클러스터 또는 사이트에서 실행 중인 다른 앱을 반대 방향으로 동시에 복제할 수 있습니다. 예를 들어, 애플리케이션 A, B, C를 데이터 센터 1에서 데이터 센터 2로 복제하고 애플리케이션 X, Y, Z를 데이터 센터 2에서 데이터 센터 1로 복제할 수 있습니다.

Astra Control을 사용하면 애플리케이션 복제와 관련된 다음 작업을 수행할 수 있습니다.

* <<복제 관계를 설정합니다>>
* <<대상 클러스터에서 복제된 앱을 온라인 상태로 전환(페일오버)>>
* <<페일오버된 복제 다시 동기화>>
* <<애플리케이션 복제를 역으로 수행합니다>>
* <<애플리케이션을 원래 소스 클러스터로 페일백합니다>>
* <<애플리케이션 복제 관계를 삭제합니다>>




== 복제 사전 요구 사항

Astra Control 애플리케이션 복제를 시작하려면 먼저 다음과 같은 사전 요구 사항을 충족해야 합니다.

* 원활한 재해 복구를 위해 세 번째 장애 도메인 또는 보조 사이트에 Astra Control Center를 배포하는 것이 좋습니다.
* 앱의 호스트 Kubernetes 클러스터 및 대상 Kubernetes 클러스터를 ONTAP 클러스터와 함께 관리해야 하며, 이상적으로는 다른 장애 도메인 또는 사이트에서 관리할 수 있어야 합니다.
* ONTAP 클러스터와 호스트 SVM이 페어링되어야 합니다. 을 참조하십시오 https://docs.netapp.com/us-en/ontap-sm-classic/peering/index.html["클러스터 및 SVM 피어링 개요"^].
* 대상 클러스터의 Astra Trident에서 페어링된 원격 SVM을 사용할 수 있어야 합니다.
* Astra Trident 버전 22.07 이상이 소스 및 대상 ONTAP 클러스터 모두에 있어야 합니다.
* 소스 및 대상 ONTAP 클러스터 모두에서 데이터 보호 번들을 사용하는 ONTAP SnapMirror 비동기식 라이센스를 설정해야 합니다. 을 참조하십시오 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["ONTAP의 SnapMirror 라이센스 개요"^].
* ONTAP 스토리지 백엔드를 Astra 제어 센터에 추가할 때 액세스 방법이 있는 "admin" 역할을 사용하여 사용자 자격 증명을 적용합니다 `http` 및 `ontapi` ONTAP 소스 클러스터와 대상 클러스터 모두에서 사용하도록 설정되었습니다. 을 참조하십시오 https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_cluster_user_accounts.html#users-list["ONTAP 설명서에서 사용자 계정을 관리합니다"^] 를 참조하십시오.
* 소스 및 대상 Kubernetes 클러스터와 ONTAP 클러스터는 Astra Control에서 관리해야 합니다.
+

NOTE: 다른 클러스터 또는 사이트에서 실행 중인 다른 앱을 반대 방향으로 동시에 복제할 수 있습니다. 예를 들어, 애플리케이션 A, B, C를 데이터 센터 1에서 데이터 센터 2로 복제하고 애플리케이션 X, Y, Z를 데이터 센터 2에서 데이터 센터 1로 복제할 수 있습니다.

* * Astra Trident/ONTAP 구성 *: Astra Control Center를 사용하려면 스토리지 클래스를 생성하고 기본 스토리지 클래스로 설정해야 합니다. Astra Control Center는 복제를 위해 Astra Trident에서 제공하는 다음과 같은 ONTAP 드라이버를 지원합니다.
+
** ONTAP - NAS
** ONTAP - NAS - 경제성(이 스토리지 클래스에는 Astra Control과 함께 SnapMirror 복제 기능을 사용할 수 없음)
** ONTAP-SAN




자세한 내용을 알아보십시오 link:../use/replicate_snapmirror.html["SnapMirror 기술을 사용하여 원격 시스템에 애플리케이션을 복제합니다"^].



== 복제 관계를 설정합니다

복제 관계를 설정하려면 복제 정책을 구성하는 다음 작업이 필요합니다.

* Astra Control에서 애플리케이션 스냅샷을 얼마나 자주 생성할지 선택(앱의 Kubernetes 리소스 및 각 앱의 볼륨에 대한 볼륨 스냅샷 포함)
* 복제 일정 선택(Kubernetes 리소스 및 영구 볼륨 데이터 포함)
* 스냅샷을 촬영할 시간 설정


.단계
. Astra Control 왼쪽 탐색 모음에서 * 응용 프로그램 * 을 선택합니다.
. 애플리케이션 페이지에서 * 데이터 보호 * > * 복제 * 탭을 선택합니다.
. 데이터 보호 > 복제 탭에서 * 복제 정책 구성 * 을 선택합니다. 또는 애플리케이션 보호 상자에서 작업 옵션을 선택하고 * 복제 정책 구성 * 을 선택합니다.
. 다음 정보를 입력하거나 선택합니다.
+
** * 대상 클러스터 *: 소스와 다른 대상 클러스터를 입력합니다.
** * 대상 스토리지 클래스 *: 대상 ONTAP 클러스터에서 쌍을 이루는 SVM을 사용하는 스토리지 클래스를 선택하거나 입력합니다.
** * 복제 유형 *: "비동기"는 현재 사용 가능한 유일한 복제 유형입니다.
** * 대상 네임스페이스 *: 대상 클러스터에 대한 새 또는 기존 대상 네임스페이스를 입력합니다.
** (선택 사항) * 네임스페이스 추가 * 를 선택하고 드롭다운 목록에서 네임스페이스를 선택하여 네임스페이스를 추가합니다.
** * 복제 빈도 *: Astra Control이 스냅샷을 생성하여 대상에 복제할 빈도를 설정합니다.
** * 오프셋 *: Astra Control에서 스냅샷을 생성할 시간(분)을 설정합니다. 다른 예약된 작업과 일치하지 않도록 오프셋을 사용할 수 있습니다.
+

TIP: 백업 및 복제 일정을 오프셋하여 일정이 겹치지 않도록 합니다. 예를 들어, 매시간 맨 위에서 백업을 수행하고 5분 오프셋 및 10분 간격으로 복제를 시작하도록 예약합니다.



. 다음 * 을 선택하고 요약을 검토하고 * 저장 * 을 선택합니다.
+

NOTE: 첫 번째 일정이 발생하기 전에 상태가 "APP-MIRROR"로 표시됩니다.

+
Astra Control은 복제에 사용되는 애플리케이션 스냅샷을 생성합니다.

. 응용 프로그램 스냅샷 상태를 보려면 * 응용 프로그램 * > * 스냅샷 * 탭을 선택합니다.
+
스냅샷 이름은 "replication-schedule-<string>" 형식을 사용합니다. Astra Control은 복제에 사용된 마지막 스냅샷을 보존합니다. 복제를 성공적으로 완료한 후에는 이전의 모든 복제 스냅샷이 삭제됩니다.



.결과
그러면 복제 관계가 생성됩니다.

Astra Control은 관계를 수립함으로써 다음과 같은 조치를 수행합니다.

* 대상에서 네임스페이스 생성(없는 경우)
* 소스 앱의 PVC에 해당하는 대상 네임스페이스에 PVC를 생성합니다.
* 애플리케이션 정합성이 보장되는 초기 Snapshot을 만듭니다.
* 초기 스냅샷을 사용하여 영구 볼륨의 SnapMirror 관계를 설정합니다.


데이터 보호 페이지에는 복제 관계 상태 및 상태가 표시됩니다. <상태>|<관계 수명 주기 상태>

예: Normal | 설정합니다

이 항목의 끝에 있는 복제 상태 및 상태에 대해 자세히 알아보십시오.



== 대상 클러스터에서 복제된 앱을 온라인 상태로 전환(페일오버)

Astra Control을 사용하면 복제된 애플리케이션을 대상 클러스터로 "페일오버"할 수 있습니다. 이 절차는 복제 관계를 중지하고 대상 클러스터에서 앱을 온라인으로 전환합니다. 이 절차를 수행해도 소스 클러스터에서 앱이 중지되지 않습니다.

.단계
. Astra Control 왼쪽 탐색 모음에서 * 응용 프로그램 * 을 선택합니다.
. 애플리케이션 페이지에서 * 데이터 보호 * > * 복제 * 탭을 선택합니다.
. 데이터 보호 > 복제 탭의 작업 메뉴에서 * 페일오버 * 를 선택합니다.
. 페일오버 페이지에서 정보를 검토하고 * 페일오버 * 를 선택합니다.


.결과
페일오버 절차로 인해 다음 작업이 수행됩니다.

* 대상 클러스터에서 최신 복제된 스냅샷을 기반으로 앱이 시작됩니다.
* 소스 클러스터와 앱(작동 중인 경우)이 중지되지 않고 계속 실행됩니다.
* 복제 상태가 "페일오버 중"으로 변경되고, 완료되면 "페일오버 실패"로 변경됩니다.
* 소스 앱의 보호 정책은 장애 조치 시 소스 앱에 있는 일정에 따라 대상 앱에 복사됩니다.
* 소스 앱에 복원 후 실행 후크가 하나 이상 활성화된 경우 해당 실행 후크가 대상 앱에 대해 실행됩니다.
* Astra Control은 소스 및 대상 클러스터와 해당 상태 모두에서 앱을 표시합니다.




== 페일오버된 복제 다시 동기화

재동기화 작업은 복제 관계를 다시 설정합니다. 관계의 소스를 선택하여 소스 또는 타겟 클러스터에 데이터를 유지할 수 있습니다. 이 작업은 SnapMirror 관계를 다시 설정하여 원하는 방향으로 볼륨 복제를 시작합니다.

이 프로세스는 복제를 다시 설정하기 전에 새 대상 클러스터에서 앱을 중지합니다.


NOTE: 재동기화 프로세스 중에 수명 주기 상태가 "설정 중"으로 표시됩니다.

.단계
. Astra Control 왼쪽 탐색 모음에서 * 응용 프로그램 * 을 선택합니다.
. 애플리케이션 페이지에서 * 데이터 보호 * > * 복제 * 탭을 선택합니다.
. 데이터 보호 > 복제 탭의 작업 메뉴에서 * 재동기화 * 를 선택합니다.
. 재동기화 페이지에서 보존할 데이터가 포함된 소스 또는 대상 앱 인스턴스를 선택합니다.
+

CAUTION: 대상의 데이터를 덮어쓰므로 재동기화 소스를 신중하게 선택합니다.

. 계속하려면 * 재동기화 * 를 선택하십시오.
. "resync"를 입력하여 확인합니다.
. 예, 재동기화 * 를 선택하여 완료합니다.


.결과
* 복제 페이지에는 복제 상태로 "설정 중"이 표시됩니다.
* Astra Control은 새 대상 클러스터에서 애플리케이션을 중지합니다.
* Astra Control은 SnapMirror 재동기화를 사용하여 선택한 방향으로 영구 볼륨 복제를 다시 설정합니다.
* 복제 페이지에는 업데이트된 관계가 표시됩니다.




== 애플리케이션 복제를 역으로 수행합니다

원래 소스 클러스터로 계속 복제하면서 애플리케이션을 대상 클러스터로 이동하기 위한 계획된 작업입니다. Astra Control은 소스 클러스터에서 애플리케이션을 중지하고 대상 클러스터에 앱을 페일오버하기 전에 데이터를 대상에 복제합니다.

이 경우 소스와 대상을 스와핑합니다. 원래 소스 클러스터가 새 대상 클러스터가 되고 원래 타겟 클러스터가 새 소스 클러스터가 됩니다.

.단계
. Astra Control 왼쪽 탐색 모음에서 * 응용 프로그램 * 을 선택합니다.
. 애플리케이션 페이지에서 * 데이터 보호 * > * 복제 * 탭을 선택합니다.
. 데이터 보호 > 복제 탭의 동작 메뉴에서 * 역방향 복제 * 를 선택합니다.
. 역방향 복제 페이지에서 정보를 검토하고 계속하려면 * 역방향 복제 * 를 선택합니다.


.결과
역방향 복제의 결과로 다음 작업이 수행됩니다.

* 원본 소스 앱의 Kubernetes 리소스 에 대한 스냅샷이 촬영됩니다.
* 앱의 Kubernetes 리소스를 삭제하여 원본 소스 앱의 Pod를 정상적으로 중지할 수 있습니다(PVC 및 PVS를 그대로 둡니다).
* 포드가 종료된 후 앱 볼륨의 스냅샷이 촬영되고 복제됩니다.
* SnapMirror 관계가 끊어져 타겟 볼륨이 읽기/쓰기 준비가 되었습니다.
* 앱의 Kubernetes 리소스는 원래 소스 애플리케이션이 종료된 후 복제된 볼륨 데이터를 사용하여 사전 종료 Snapshot에서 복원됩니다.
* 복제는 반대 방향으로 다시 설정됩니다.




== 애플리케이션을 원래 소스 클러스터로 페일백합니다

Astra Control을 사용하면 다음과 같은 일련의 작업을 통해 "장애 조치" 작업 후에 "장애 복구"를 달성할 수 있습니다. 이 워크플로우에서 원래 복제 방향을 복구하기 위해 Astra Control은 복제 방향을 바꾸기 전에 애플리케이션 변경 사항을 원래 소스 클러스터로 복제(재동기화)합니다.

이 프로세스는 대상에 대한 장애 조치를 완료한 관계로부터 시작되며 다음 단계를 포함합니다.

* 페일오버된 상태로 시작합니다.
* 관계를 다시 동기화합니다.
* 복제를 역으로 수행합니다.


.단계
. Astra Control 왼쪽 탐색 모음에서 * 응용 프로그램 * 을 선택합니다.
. 애플리케이션 페이지에서 * 데이터 보호 * > * 복제 * 탭을 선택합니다.
. 데이터 보호 > 복제 탭의 작업 메뉴에서 * 재동기화 * 를 선택합니다.
. 장애 복구 작업의 경우 페일오버된 앱을 재동기화 작업의 소스로 선택합니다(기록된 모든 데이터 장애 조치 유지).
. "resync"를 입력하여 확인합니다.
. 예, 재동기화 * 를 선택하여 완료합니다.
. 재동기화가 완료되면 데이터 보호 > 복제 탭의 동작 메뉴에서 * 역방향 복제 * 를 선택합니다.
. 역방향 복제 페이지에서 정보를 검토하고 * 역방향 복제 * 를 선택합니다.


.결과
이렇게 하면 "재동기화" 및 "역관계" 작업의 결과가 결합되어 원래 소스 클러스터에서 애플리케이션이 온라인 상태가 되고 복제가 원래 대상 클러스터로 다시 시작됩니다.



== 애플리케이션 복제 관계를 삭제합니다

관계를 삭제하면 두 개의 별도 앱이 서로 관계가 없습니다.

.단계
. Astra Control 왼쪽 탐색 모음에서 * 응용 프로그램 * 을 선택합니다.
. 애플리케이션 페이지에서 * 데이터 보호 * > * 복제 * 탭을 선택합니다.
. 데이터 보호 > 복제 탭의 애플리케이션 보호 상자 또는 관계 다이어그램에서 * 복제 관계 삭제 * 를 선택합니다.


.결과
복제 관계를 삭제하면 다음과 같은 작업이 수행됩니다.

* 관계가 설정되었지만 대상 클러스터에서 앱이 아직 온라인 상태가 되지 않은 경우(장애 발생) Astra Control은 초기화 중에 생성된 PVC를 유지하고 "비어 있는" 관리 앱을 대상 클러스터에 남겨두고 생성된 백업을 유지할 수 있도록 대상 앱을 유지합니다.
* 대상 클러스터에서 앱이 온라인 상태가 된 경우(장애 발생), Astra Control은 PVC 및 대상 앱을 유지합니다. 이제 소스 및 대상 앱이 독립 앱으로 취급됩니다. 백업 스케줄은 두 애플리케이션 모두에 유지되지만 서로 연결되지 않습니다. 




== 복제 관계 상태 및 관계 수명 주기 상태입니다

Astra Control은 복제 관계의 관계 상태와 수명 주기의 상태를 표시합니다.



=== 복제 관계 상태

다음 상태는 복제 관계의 상태를 나타냅니다.

* * 정상 *: 관계가 설정되었거나 설정되었으며 최근 스냅샷이 성공적으로 전송되었습니다.
* * 경고 *: 관계가 페일오버되었거나 페일오버되었습니다(따라서 소스 앱을 더 이상 보호하지 않음).
* * 심각 *
+
** 관계가 설정 또는 페일오버되고 마지막 조정 시도가 실패했습니다.
** 관계가 성립되고 새로운 PVC의 추가를 조정하기 위한 마지막 시도가 실패합니다.
** 관계가 설정되지만(성공한 스냅샷은 복제되고 페일오버는 가능) 가장 최근의 스냅샷이 실패했거나 복제하지 못했습니다.






=== 복제 수명 주기 상태입니다

다음 상태는 복제 주기의 여러 단계를 반영합니다.

* * 설정 *: 새 복제 관계가 생성됩니다. Astra Control은 필요한 경우 네임스페이스를 생성하고, 대상 클러스터의 새 볼륨에 지속적인 PVC(Volume Claim)를 생성하여 SnapMirror 관계를 생성합니다. 이 상태는 복제가 재동기화 중이거나 복제 재동기화 중임을 나타낼 수도 있습니다.
* * 설정됨 *: 복제 관계가 있습니다. Astra Control은 주기적으로 PVC가 사용 가능한지 확인하고, 복제 관계를 확인하고, 정기적으로 앱의 스냅샷을 생성하고, 앱에서 새로운 소스 PVC를 식별합니다. 이 경우 Astra Control은 복제에 포함할 리소스를 생성합니다.
* * 페일오버 *: Astra Control은 SnapMirror 관계를 중단시키고 마지막으로 성공한 복제 애플리케이션 Snapshot에서 앱의 Kubernetes 리소스를 복원합니다.
* * 페일오버됨 *: Astra Control은 소스 클러스터에서 복제를 중지하고, 대상에서 최근(성공한) 복제 앱 Snapshot을 사용하고, Kubernetes 리소스를 복원합니다.
* * 재동기화 *: Astra Control SnapMirror 재동기화를 사용하여 재동기화 소스의 새 데이터를 재동기화 대상으로 재동기화합니다. 이 작업은 동기화 방향에 따라 대상의 일부 데이터를 덮어쓸 수 있습니다. Astra Control은 대상 네임스페이스에서 실행 중인 앱을 중지하고 Kubernetes 앱을 제거합니다. 재동기화 프로세스 중에 상태가 "설정 중"으로 표시됩니다.
* * 후진 *: 은 원래 소스 클러스터로 계속 복제하면서 애플리케이션을 대상 클러스터로 이동하기 위한 계획된 작업입니다. Astra Control은 소스 클러스터에서 애플리케이션을 중지하고, 대상 클러스터에 앱을 페일오버하기 전에 데이터를 대상에 복제합니다. 역방향 복제 중에 상태가 "설정 중"으로 표시됩니다.
* * 삭제 *:
+
** 복제 관계가 설정되었지만 아직 페일오버되지 않은 경우 Astra Control은 복제 중에 생성된 PVC를 제거하고 대상 관리 앱을 삭제합니다.
** 복제가 이미 실패한 경우 Astra Control은 PVC 및 대상 앱을 유지합니다.



