---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster, kubernetes, astra, astra control 
summary: Astra Control에서 더 이상 관리하지 않으려는 애플리케이션 또는 컴퓨팅 제거 
---
= 앱 및 클러스터 관리를 취소합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control Center에서 더 이상 관리하지 않으려는 응용 프로그램 또는 클러스터를 제거합니다.



== 앱 관리를 취소합니다

Astra Control Center에서 더 이상 백업, 스냅샷 또는 클론 복제하지 않을 애플리케이션 관리를 중지합니다.

앱 관리를 취소하는 경우:

* 기존 백업 및 스냅샷이 삭제됩니다.
* 애플리케이션과 데이터는 사용 가능한 상태로 유지됩니다.


.단계
. 왼쪽 탐색 모음에서 * 응용 프로그램 * 을 선택합니다.
. 앱을 선택합니다.
. 작업 열의 옵션 메뉴에서 * 관리 취소 * 를 선택합니다.
. 정보를 검토합니다.
. "unmanage"를 입력하여 확인합니다.
. 예, 응용 프로그램 관리 취소 * 를 선택합니다.


.결과
Astra Control Center가 앱 관리를 중지합니다.



== 클러스터 관리를 취소합니다

Astra Control Center에서 더 이상 관리하지 않으려는 클러스터 관리를 중지합니다.


NOTE: 클러스터를 관리하기 전에 클러스터와 연결된 앱의 관리를 해제해야 합니다.

클러스터 관리를 취소하는 경우:

* 이 작업을 수행하면 Astra Control Center에서 클러스터를 관리할 수 없습니다. 클러스터 구성을 변경하지 않고 클러스터를 삭제하지 않습니다.
* Astra Control Provisioner 또는 Astra Trident는 클러스터에서 제거되지 않습니다. https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Astra Trident를 제거하는 방법을 알아보십시오"^].


.단계
. 왼쪽 탐색 모음에서 * 클러스터 * 를 선택합니다.
. 더 이상 관리하지 않으려는 클러스터의 확인란을 선택합니다.
. Actions * 열의 Options 메뉴에서 * Unmanage * 를 선택합니다.
. 클러스터 관리를 해제할지 확인한 다음 * 예, 클러스터 관리 취소 * 를 선택합니다.


.결과
클러스터의 상태가 * Removing * 으로 변경됩니다. 그 이후에는 클러스터가 * Clusters * 페이지에서 제거되고 Astra Control Center에서 더 이상 관리되지 않습니다.


IMPORTANT: 클러스터의 관리를 취소하면 원격 측정 데이터를 전송하기 위해 설치된 모든 리소스가 제거됩니다.
