---
sidebar: sidebar 
permalink: use/view-clusters.html 
keywords: view cluster, edit storage class, storage class, cluster storage, cluster overview 
summary: Astra Control Center에 클러스터를 추가한 후에는 클러스터의 위치, 작업자 노드, 영구 볼륨 및 스토리지 클래스와 같은 클러스터에 대한 세부 정보를 볼 수 있습니다. 기본 스토리지 클래스를 변경할 수도 있습니다. 
---
= 클러스터 상태를 보고 스토리지 클래스를 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control Center에서 관리할 클러스터를 추가한 후에는 클러스터의 위치, 작업자 노드, 영구 볼륨 및 스토리지 클래스 등의 클러스터에 대한 세부 정보를 볼 수 있습니다. 관리 클러스터의 기본 스토리지 클래스를 변경할 수도 있습니다.



== 클러스터 상태 및 세부 정보 보기

클러스터의 위치, 작업자 노드, 영구 볼륨 및 스토리지 클래스와 같은 클러스터에 대한 세부 정보를 볼 수 있습니다.

.단계
. Astra Control Center UI에서 * Clusters * 를 선택합니다.
. 클러스터 * 페이지에서 세부 정보를 확인할 클러스터를 선택합니다.
+

NOTE: 클러스터가 인 경우 `removed` 클러스터 및 네트워크 연결이 양호해 보이지만(Kubernetes API를 사용하여 클러스터에 액세스하려는 외부 시도가 성공한 경우), Astra Control에 제공한 kubeconfig는 더 이상 유효하지 않을 수 있습니다. 클러스터의 인증서 순환 또는 만료 때문일 수 있습니다. 이 문제를 해결하려면 을 사용하여 Astra Control의 클러스터와 연결된 자격 증명을 업데이트하십시오 https://docs.netapp.com/us-en/astra-automation["Astra Control API를 참조하십시오"].

. Overview *, * Storage * 및 * Activity * 탭에서 원하는 정보를 확인할 수 있습니다.
+
** * 개요 *: 해당 상태를 포함한 작업자 노드에 대한 세부 정보.
** * 스토리지 *: 스토리지 클래스 및 상태를 비롯하여 컴퓨팅과 연관된 영구 볼륨입니다.
** * Activity *: 클러스터와 관련된 활동을 표시합니다.





NOTE: Astra Control Center * 대시보드 * 부터 클러스터 정보를 볼 수도 있습니다. 리소스 요약 * 의 * 클러스터 * 탭에서 * 클러스터 * 페이지로 이동하는 관리 클러스터를 선택할 수 있습니다. 클러스터 * 페이지로 이동한 후 위에 설명된 단계를 따릅니다.



== 기본 스토리지 클래스를 변경합니다

클러스터의 기본 스토리지 클래스를 변경할 수 있습니다. Astra Control이 클러스터를 관리할 때 클러스터의 기본 스토리지 클래스를 추적합니다.


NOTE: kubbeck 명령을 사용하여 스토리지 클래스를 변경하지 마십시오. 대신 이 절차를 사용하십시오. kubectl을 사용하면 Astra Control이 변경 사항을 되돌립니다.

.단계
. Astra Control Center 웹 UI에서 * Clusters * 를 선택합니다.
. 클러스터 * 페이지에서 변경할 클러스터를 선택합니다.
. Storage * 탭을 선택합니다.
. 스토리지 클래스 * 범주를 선택합니다.
. 기본값으로 설정할 스토리지 클래스에 대해 * Actions * 메뉴를 선택합니다.
. Set as default * 를 선택합니다.

