---
sidebar: sidebar 
permalink: get-started/add-bucket.html 
keywords: set up astra control, add bucket 
summary: Astra Control Center를 설치한 후에는 설정 시 버킷을 추가하는 것을 고려해야 합니다. 
---
= 버킷을 추가합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control UI 또는 를 사용하여 버킷을 추가할 수 있습니다 https://docs.netapp.com/us-en/astra-automation["Astra Control API를 참조하십시오"^]. 애플리케이션과 영구 스토리지를 백업하려는 경우나 클러스터 간에 애플리케이션을 클론 복제하려는 경우에는 오브젝트 저장소 버킷 공급자를 추가하는 것이 중요합니다. Astra Control은 이러한 백업 또는 클론을 정의한 오브젝트 저장소 버킷에 저장합니다.

애플리케이션 구성과 영구 스토리지를 동일한 클러스터에 클론 복제하려는 경우 Astra Control에 버킷이 필요하지 않습니다. 애플리케이션 스냅샷 기능에는 버킷이 필요하지 않습니다.

.시작하기 전에
* Astra Control Center에서 관리하는 클러스터에서 연결할 수 있는 버킷이 있어야 합니다.
* 버킷에 대한 자격 증명이 있는지 확인하십시오.
* 버킷이 다음 유형 중 하나인지 확인합니다.
+
** NetApp ONTAP S3
** NetApp StorageGRID S3
** Microsoft Azure를 참조하십시오
** 일반 S3





NOTE: AWS(Amazon Web Services) 및 GCP(Google Cloud Platform)는 일반 S3 버킷 유형을 사용합니다.


NOTE: Astra Control Center는 Amazon S3를 일반 S3 버킷 공급자로 지원하지만, Astra Control Center는 Amazon의 S3 지원을 주장하는 모든 오브젝트 저장소 공급업체를 지원하지 않을 수 있습니다.

.단계
. 왼쪽 탐색 영역에서 * Bucket * 을 선택합니다.
. 추가 * 를 선택합니다.
. 버킷 유형을 선택합니다.
+

NOTE: 버킷을 추가할 때 올바른 버킷 공급자를 선택하고 해당 공급자에 적합한 자격 증명을 제공합니다. 예를 들어, UI에서 NetApp ONTAP S3를 유형으로 받아들이고 StorageGRID 자격 증명을 받아들이지만, 이 버킷을 사용한 이후의 모든 애플리케이션 백업 및 복원이 실패합니다.

. 기존 버킷 이름과 선택적 설명을 입력합니다.
+

TIP: 버킷 이름과 설명은 나중에 백업을 생성할 때 선택할 수 있는 백업 위치로 나타납니다. 이 이름은 보호 정책 구성 중에도 표시됩니다.

. S3 엔드포인트의 이름 또는 IP 주소를 입력합니다.
. 자격 증명 선택 * 에서 * 추가 * 또는 * 기존 * 사용 탭을 선택합니다.
+
** 추가 * 를 선택한 경우:
+
... Astra Control의 다른 자격 증명과 구별되는 자격 증명의 이름을 입력합니다.
... 클립보드의 내용을 붙여 넣어 액세스 ID와 비밀 키를 입력합니다.


** 기존 사용 * 을 선택한 경우:
+
... 버킷에 사용할 기존 자격 증명을 선택합니다.




. 를 선택합니다 `Add`.
+

NOTE: 버킷을 추가하면 Astra Control이 기본 버킷 표시기로 하나의 버킷을 표시합니다. 사용자가 만든 첫 번째 버킷이 기본 버킷이 됩니다. 양동이 추가될 때 나중에 결정할 수 있습니다 link:../use/manage-buckets.html#set-the-default-bucket["다른 기본 버킷을 설정합니다"].


