---
sidebar: sidebar 
permalink: get-started/add-license.html 
keywords: set up astra control, astra control license 
summary: Astra Control Center를 설치하고 UI에 로그인하여 암호를 변경하면 라이센스를 설정할 수 있습니다. 
---
= Astra Control Center에 대한 라이센스를 추가합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Center를 설치할 때 포함된 평가판 라이센스가 이미 설치되어 있습니다. Astra Control Center를 평가하는 경우 이 단계를 건너뛸 수 있습니다.

Astra Control UI 또는 를 사용하여 새 라이센스를 추가할 수 있습니다 https://docs.netapp.com/us-en/astra-automation["Astra Control API를 참조하십시오"^].

Astra Control Center 라이센스는 Kubernetes CPU 유닛을 사용하여 CPU 리소스를 측정하고, 모든 관리되는 Kubernetes 클러스터의 작업자 노드에 할당된 CPU 리소스를 고려합니다. 라이센스는 vCPU 사용량을 기준으로 합니다. 라이선스 계산 방법에 대한 자세한 내용은 을 참조하십시오 link:../concepts/licensing.html["라이센싱"].


NOTE: 설치가 라이센스 CPU 유닛 수를 초과하여 증가할 경우, Astra Control Center를 통해 새 애플리케이션을 관리할 수 없습니다. 용량이 초과되면 경고가 표시됩니다.


NOTE: 기존 평가판 또는 전체 라이센스를 업데이트하려면 을 참조하십시오 link:../use/update-licenses.html["기존 라이센스를 업데이트합니다"].

.시작하기 전에
* 새로 설치된 Astra Control Center 인스턴스에 액세스합니다.
* 관리자 역할 권한.
* A link:../concepts/licensing.html["NetApp 라이센스 파일"] (NLF)


.단계
. Astra Control Center UI에 로그인합니다.
. 계정 * > * 라이센스 * 를 선택합니다.
. 라이센스 추가 * 를 선택합니다.
. 다운로드한 라이센스 파일(NLF)으로 이동합니다.
. 라이센스 추가 * 를 선택합니다.


계정 * > * 라이센스 * 페이지에는 라이센스 정보, 만료 날짜, 라이센스 일련 번호, 계정 ID 및 사용된 CPU 단위가 표시됩니다.


NOTE: 평가판 라이센스가 있고 데이터를 AutoSupport로 전송하지 않는 경우, Astra Control Center에 장애가 발생할 경우 데이터 손실을 방지하기 위해 계정 ID를 저장해야 합니다.
