---
sidebar: sidebar 
permalink: get-started/faq.html 
keywords: astra faq, astra frequently asked questions, what is astra, astra control, kubernetes, persistent volumes 
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= Astra Control Center에 대한 질문과 대답
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 개요

다음 섹션에서는 Astra Control Center를 사용할 때 나타날 수 있는 몇 가지 추가 질문에 대한 답변을 제공합니다. 자세한 내용은 astra.feedback@netapp.com 으로 문의하십시오



== Astra Control Center에 액세스할 수 있습니다

* Astra Control URL은 무엇입니까? *

Astra Control Center는 로컬 인증과 각 환경에 고유한 URL을 사용합니다.

URL의 경우 브라우저에서 Astra_control_center.YAML 사용자 지정 리소스(CR) 파일을 설치할 때 spec.astraAddress 필드에 설정한 FQDN(정규화된 도메인 이름)을 입력합니다. 이메일은 Astra_control_center.YAML CR의 spec.email 필드에 설정한 값입니다.



== 라이센싱

* 평가판 라이센스를 사용하고 있습니다. 전체 라이센스로 변경하려면 어떻게 해야 합니까? *

NetApp에서 NLF(NetApp 라이센스 파일)를 받아 전체 라이센스로 쉽게 변경할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 계정 * > * 라이센스 * 를 선택합니다.
. 라이센스 개요 에서 라이센스 정보 오른쪽에 있는 옵션 메뉴를 선택합니다.
. 바꾸기 * 를 선택합니다.
. 다운로드한 라이센스 파일을 찾아 * 추가 * 를 선택합니다.


* 평가판 라이센스를 사용하고 있습니다. 앱을 관리할 수 있습니까? *

예. 평가판 라이센스를 사용하여 관리 앱 기능을 테스트할 수 있습니다(기본적으로 설치되는 포함된 평가판 라이센스 포함). 평가판 라이센스와 전체 라이센스 간의 기능 또는 기능은 차이가 없으며 평가판 라이센스의 수명도 짧아집니다. 을 참조하십시오 link:../concepts/licensing.html["라이센싱"^] 를 참조하십시오.



== Kubernetes 클러스터를 등록하는 중입니다

* Astra Control에 추가한 후 Kubernetes 클러스터에 작업자 노드를 추가해야 합니다. 어떻게 해야 합니까? *

새 작업자 노드를 기존 풀에 추가할 수 있습니다. 이러한 정보는 Astra Control에서 자동으로 발견됩니다. Astra Control에서 새 노드가 보이지 않으면 새 작업자 노드가 지원되는 이미지 유형을 실행하고 있는지 확인합니다. kubeck get nodes 명령을 사용하여 새 작업자 노드의 상태를 확인할 수도 있습니다.

* 클러스터를 올바르게 관리하려면 어떻게 해야 합니까? *

. link:../use/unmanage.html["Astra Control에서 애플리케이션을 관리합니다"].
. link:../use/unmanage.html#stop-managing-compute["Astra Control에서 클러스터 관리를 해제합니다"].


* Astra Control에서 Kubernetes 클러스터를 제거한 후 애플리케이션과 데이터는 어떻게 됩니까? *

Astra Control에서 클러스터를 제거해도 클러스터의 구성(애플리케이션 및 영구 스토리지)은 변경되지 않습니다. Astra Control 스냅샷 또는 해당 클러스터의 애플리케이션 백업을 복구할 수 없습니다. Astra Control에서 생성한 영구 스토리지 백업은 Astra Control 내에 남아 있지만 복구할 수 없습니다.


WARNING: 다른 방법을 통해 클러스터를 삭제하기 전에 항상 Astra Control에서 클러스터를 제거하십시오. Astra Control에서 관리하는 다른 도구를 사용하여 클러스터를 삭제하면 Astra Control 계정에 문제가 발생할 수 있습니다.

* 관리를 해제하면 NetApp Astra Trident가 클러스터에서 자동으로 제거됩니까? * Astra Control Center에서 클러스터를 관리할 경우 Astra Trident가 클러스터에서 자동으로 제거되지 않습니다. Astra Trident를 제거하려면 다음을 수행해야 합니다 https://["Astra Trident 문서의 다음 단계를 따릅니다"^].



== 응용 프로그램 관리

* Astra Control이 응용 프로그램을 배포할 수 있습니까? *

Astra Control은 애플리케이션을 배포하지 않습니다. 응용 프로그램은 Astra Control 외부에서 배포해야 합니다.

* Astra Control에서 관리를 중지한 후 응용 프로그램은 어떻게 됩니까? *

기존 백업 또는 스냅샷이 삭제됩니다. 애플리케이션과 데이터는 사용 가능한 상태로 유지됩니다. 관리되지 않는 응용 프로그램 또는 해당 응용 프로그램에 속한 백업 또는 스냅숏에는 데이터 관리 작업을 사용할 수 없습니다.

* Astra Control이 NetApp이 아닌 스토리지에 있는 애플리케이션을 관리할 수 있습니까? *

아니요 Astra Control은 NetApp이 아닌 스토리지를 사용하는 애플리케이션을 검색할 수 있지만, NetApp이 아닌 스토리지를 사용하는 애플리케이션은 관리할 수 없습니다.

"Astra Control을 자체적으로 관리해야 합니까?" *

아니요, Astra Control 자체는 "시스템 응용 프로그램"이기 때문에 관리하지 않아야 합니다.

* 비정상적인 포드가 앱 관리에 영향을 미칩니까? *

아니요. Pod의 상태는 앱 관리에 영향을 주지 않습니다.



== 데이터 관리 작업

* My Application은 여러 PVS를 사용합니다. Astra Control은 이러한 PVS의 스냅샷과 백업을 수행합니까? *

예. Astra Control의 애플리케이션에 대한 스냅샷 작업에는 애플리케이션의 PVC에 바인딩된 모든 PVS의 스냅샷이 포함됩니다.

* Astra Control에서 생성한 스냅샷을 다른 인터페이스 또는 객체 스토리지를 통해 직접 관리할 수 있습니까? *

아니요 Astra Control에서 생성한 스냅샷 및 백업은 Astra Control에서만 관리할 수 있습니다.
