---
sidebar: sidebar 
permalink: get-started/prep-for-cluster-management.html 
keywords: set up astra control, astra control license, add cluster, add storage backend, import storage, add bucket 
summary: Astra Control Center를 설치하고 UI에 로그인하여 암호를 변경하면 클러스터를 추가하기 위한 사전 요구사항이 충족되는지 확인할 수 있습니다. 
---
= Astra Control을 사용하여 클러스터 관리를 위한 환경을 준비합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
클러스터를 추가하기 전에 다음 전제 조건이 충족되어야 합니다. 또한 자격 검사를 실행하여 클러스터를 Astra Control Center에 추가할 준비가 되었는지 확인하고 필요에 따라 kubeconfig 클러스터 역할을 생성해야 합니다.

Astra Control을 사용하면 환경 및 선호도에 따라 CR(Custom Resource) 또는 kubeconfig로 관리되는 클러스터를 추가할 수 있습니다.

.시작하기 전에
* * 환경 필수 조건 충족 *: 사용자 환경이 충족됩니다 link:../get-started/requirements.html["구현할 수 있습니다"] Astra Control Center의 경우
* * 작업자 노드 구성 *: 확인하십시오 https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html["작업자 노드를 구성합니다"^] 클러스터에서 Pod가 백엔드 스토리지와 상호 작용할 수 있도록 적절한 스토리지 드라이버가 있어야 합니다.


* [[enable-psa]] * PSA 제한 활성화 *: 클러스터에 Kubernetes 1.25 이상 클러스터의 표준인 Pod 보안 허용 적용이 활성화되어 있으면 이 네임스페이스에 PSA 제한을 활성화해야 합니다.
+
** `netapp-acc-operator` 네임스페이스:
+
[listing]
----
kubectl label --overwrite ns netapp-acc-operator pod-security.kubernetes.io/enforce=privileged
----
** `netapp monitoring` 네임스페이스:
+
[listing]
----
kubectl label --overwrite ns netapp-monitoring pod-security.kubernetes.io/enforce=privileged
----


* * ONTAP credentials *: Astra Control Center를 사용하여 앱을 백업 및 복원하려면 ONTAP 시스템에 ONTAP 자격 증명과 고급 사용자 및 사용자 ID가 설정되어 있어야 합니다.
+
ONTAP 명령줄에서 다음 명령을 실행합니다.

+
[listing]
----
export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -superuser sys
export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -anon 65534
----
* * kubeconfig-managed cluster requirements *: 이 요구 사항은 kubeconfig로 관리되는 앱 클러스터에 적용됩니다.
+
** * kubeconfig 액세스 할 수 있습니다 * : 당신은 액세스 할 수 있습니다 https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["기본 클러스터 kubecononfig"^] 그것입니다 link:../get-started/install_acc.html#set-up-namespace-and-secret-for-registries-with-auth-requirements["설치하는 동안 를 구성했습니다"^].
** * 인증 기관 고려 사항 *: 개인 CA(인증 기관)를 참조하는 kubeconfig 파일을 사용하여 클러스터를 추가하는 경우 에 다음 줄을 추가하십시오 `cluster` kubeconfig 파일의 섹션. 이를 통해 Astra Control이 클러스터를 추가할 수 있습니다.
+
[listing]
----
insecure-skip-tls-verify: true
----
** * Rancher 전용 *: Rancher 환경에서 애플리케이션 클러스터를 관리할 때 Rancher가 제공하는 kubecon무화과 파일에서 애플리케이션 클러스터의 기본 컨텍스트를 수정하여 Rancher API 서버 컨텍스트 대신 컨트롤 플레인 컨텍스트를 사용합니다. 따라서 Rancher API 서버의 부하가 줄어들고 성능이 향상됩니다.


* * Astra Control Provisioner 요구 사항 *: 클러스터를 관리하려면 Astra Trident 구성 요소를 포함하여 올바르게 구성된 Astra Control Provisioner가 있어야 합니다.
+
** * Astra Trident 환경 요구 사항 검토 *: Astra Control Provisioner를 설치 또는 업그레이드하기 전에 를 검토하십시오 https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["지원되는 프런트엔드, 백엔드 및 호스트 구성"^].
** * Astra Control Provisioner 기능 활성화 *: Astra Trident 23.10 이상을 설치하고 활성화하는 것이 좋습니다 link:../get-started/enable-acp.html["Astra Control Provisioner 고급 스토리지 기능"]. 향후 릴리즈에서 Astra Control Provisioner가 활성화되어 있지 않으면 Astra Control이 Astra Trident를 지원하지 않습니다.
** * 스토리지 백엔드 구성 *: 최소 하나의 스토리지 백엔드가 있어야 합니다 https://docs.netapp.com/us-en/trident/trident-use/backends.html["Astra Trident에서 구성됨"^] 클러스터에서.
** * 스토리지 클래스 구성 *: 최소 하나의 스토리지 클래스가 있어야 합니다 https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["Astra Trident에서 구성됨"^] 클러스터에서. 기본 저장소 클래스가 구성된 경우 기본 주석이 있는 * 전용 * 저장소 클래스인지 확인합니다.
** * 볼륨 스냅샷 컨트롤러 구성 및 볼륨 스냅샷 클래스 설치 *: https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["볼륨 스냅샷 컨트롤러를 설치합니다"] 따라서 Astra Control에서 스냅샷을 생성할 수 있습니다. https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#create-a-volume-snapshot["생성"^] 하나 이상 `VolumeSnapshotClass` Astra Trident 사용:






== 자격 검사를 실행합니다

다음 자격 검사를 실행하여 클러스터를 Astra Control Center에 추가할 준비가 되었는지 확인합니다.

.단계
. 실행 중인 Astra Trident 버전을 확인합니다.
+
[source, console]
----
kubectl get tridentversion -n trident
----
+
Astra Trident가 있으면 다음과 유사한 출력이 표시됩니다.

+
[listing]
----
NAME      VERSION
trident   24.02.0
----
+
Astra Trident가 없으면 다음과 유사한 출력이 표시됩니다.

+
[listing]
----
error: the server doesn't have a resource type "tridentversions"
----
. 다음 중 하나를 수행합니다.
+
** Astra Trident 23.01 이하를 실행 중인 경우 다음을 사용합니다 https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html["지침"^] Astra Control Provisioner로 업그레이드하기 전에 Astra Trident의 최신 버전으로 업그레이드하십시오. 가능합니다 link:../get-started/enable-acp.html["직접 업그레이드를 수행합니다"] Astra Trident가 버전 24.02의 4개 릴리즈 윈도우 내에 있는 경우 Astra Control Provisioner 24.02에 등록됩니다. 예를 들어, Astra Trident 23.04에서 Astra Control Provisioner 24.02로 직접 업그레이드할 수 있습니다.
** Astra Trident 23.10 이상을 실행 중인 경우 Astra Control Provisioner가 설치되었는지 확인합니다 link:../get-started/faq.html#running-acp-check["활성화됨"]. Astra Control Provisioner는 23.10 이전 Astra Control Center 릴리즈에서 작동하지 않습니다. link:../get-started/enable-acp.html["Astra Control Provisioner를 업그레이드합니다"] 최신 기능에 액세스하기 위해 업그레이드하는 Astra Control Center와 동일한 버전을 사용합니다.


. 모든 Pod(포함)가 `trident-acp`) 실행 중:
+
[source, console]
----
kubectl get pods -n trident
----
. 스토리지 클래스가 지원되는 Astra Trident 드라이버를 사용하고 있는지 확인합니다. 공급자 이름은 이어야 합니다 `csi.trident.netapp.io`. 다음 예를 참조하십시오.
+
[source, console]
----
kubectl get sc
----
+
샘플 반응:

+
[listing]
----
NAME                  PROVISIONER            RECLAIMPOLICY  VOLUMEBINDINGMODE  ALLOWVOLUMEEXPANSION  AGE
ontap-gold (default)  csi.trident.netapp.io  Delete         Immediate          true                  5d23h
----




== 클러스터 역할 kubecononfig를 생성합니다

kubeconfig를 사용하여 관리되는 클러스터의 경우 Astra Control Center에 대해 제한된 권한 또는 확장된 권한 관리자 역할을 선택적으로 생성할 수 있습니다. 이미 의 일부로 kubecononfig를 구성했으므로 Astra Control Center 설정에 필요한 절차는 아닙니다 link:../get-started/install_acc.html#set-up-namespace-and-secret-for-registries-with-auth-requirements["설치 프로세스"].

다음 시나리오 중 하나가 사용자 환경에 적용되는 경우 이 절차를 통해 별도의 kubecononfig를 생성할 수 있습니다.

* 관리하는 클러스터에 대한 Astra Control 권한을 제한하려고 합니다
* 여러 개의 컨텍스트를 사용하며 설치 중에 구성된 기본 Astra Control kubecononfig를 사용할 수 없거나, 단일 컨텍스트의 제한된 역할은 사용자 환경에서 작동하지 않습니다


.시작하기 전에
절차 단계를 완료하기 전에 관리하려는 클러스터에 대해 다음 사항을 확인해야 합니다.

* kubbtl v1.23 이상이 설치되었습니다
* Astra Control Center를 통해 추가하고 관리하려는 클러스터에 kubctl 액세스를 허용합니다
+

NOTE: 이 절차를 수행하려면 Astra Control Center를 실행 중인 클러스터에 kubectl을 액세스할 필요가 없습니다.

* 활성 컨텍스트에 대한 클러스터 관리자 권한으로 관리하려는 클러스터에 대한 활성 kubecononfig입니다


.단계
. 서비스 계정 생성:
+
.. astractrol-service-account.yaML이라는 서비스 계정 파일을 만듭니다.
+
[source, subs="specialcharacters,quotes"]
----
*astracontrol-service-account.yaml*
----
+
[source, yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: astracontrol-service-account
  namespace: default
----
.. 서비스 계정 적용:
+
[source, console]
----
kubectl apply -f astracontrol-service-account.yaml
----


. Astra Control에서 클러스터를 관리할 수 있는 충분한 권한을 가진 다음 클러스터 역할 중 하나를 생성합니다.
+
[role="tabbed-block"]
====
.제한된 클러스터 역할
--
이 역할에는 Astra Control에서 관리할 클러스터를 관리하는 데 필요한 최소 권한이 포함되어 있습니다.

.. 을 생성합니다 `ClusterRole` 호출되는 파일(예: `astra-admin-account.yaml`.
+
[source, subs="specialcharacters,quotes"]
----
*astra-admin-account.yaml*
----
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astra-admin-account
rules:

# Get, List, Create, and Update all resources
# Necessary to backup and restore all resources in an app
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - create
  - patch

# Delete Resources
# Necessary for in-place restore and AppMirror failover
- apiGroups:
  - ""
  - apps
  - autoscaling
  - batch
  - crd.projectcalico.org
  - extensions
  - networking.k8s.io
  - policy
  - rbac.authorization.k8s.io
  - snapshot.storage.k8s.io
  - trident.netapp.io
  resources:
  - configmaps
  - cronjobs
  - daemonsets
  - deployments
  - horizontalpodautoscalers
  - ingresses
  - jobs
  - namespaces
  - networkpolicies
  - persistentvolumeclaims
  - poddisruptionbudgets
  - pods
  - podtemplates
  - replicasets
  - replicationcontrollers
  - replicationcontrollers/scale
  - rolebindings
  - roles
  - secrets
  - serviceaccounts
  - services
  - statefulsets
  - tridentmirrorrelationships
  - tridentsnapshotinfos
  - volumesnapshots
  - volumesnapshotcontents
  verbs:
  - delete

# Watch resources
# Necessary to monitor progress
- apiGroups:
  - ""
  resources:
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  verbs:
  - watch

# Update resources
- apiGroups:
  - ""
  - build.openshift.io
  - image.openshift.io
  resources:
  - builds/details
  - replicationcontrollers
  - replicationcontrollers/scale
  - imagestreams/layers
  - imagestreamtags
  - imagetags
  verbs:
  - update
----
.. (OpenShift 클러스터에만 해당) 의 끝에 다음을 추가합니다 `astra-admin-account.yaml` 파일:
+
[source, console]
----
# OpenShift security
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  - update
----
.. 클러스터 역할 적용:
+
[source, console]
----
kubectl apply -f astra-admin-account.yaml
----


--
.클러스터 역할이 확장되었습니다
--
이 역할에는 Astra Control에서 관리할 클러스터에 대한 확장된 권한이 포함됩니다. 여러 컨텍스트를 사용하고 설치 중에 구성된 기본 Astra Control kubecononfig를 사용할 수 없거나 단일 컨텍스트의 제한된 역할을 사용할 수 없는 경우 이 역할을 사용할 수 있습니다.


NOTE: 다음 사항을 참조하십시오 `ClusterRole` 일반 Kubernetes의 예는 단계입니다. 사용자 환경에 대한 지침은 Kubernetes 배포 문서를 참조하십시오.

.. 을 생성합니다 `ClusterRole` 호출되는 파일(예: `astra-admin-account.yaml`.
+
[source, subs="specialcharacters,quotes"]
----
*astra-admin-account.yaml*
----
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astra-admin-account
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
----
.. 클러스터 역할 적용:
+
[source, console]
----
kubectl apply -f astra-admin-account.yaml
----


--
====
. 클러스터 역할에 대한 클러스터 역할 바인딩을 서비스 계정에 생성합니다.
+
.. astracontrol-clusterrobinding.YAML이라는 ClusterRoleBinding 파일을 만듭니다.
+
[source, subs="specialcharacters,quotes"]
----
*astracontrol-clusterrolebinding.yaml*
----
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: astracontrol-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: astra-admin-account
subjects:
- kind: ServiceAccount
  name: astracontrol-service-account
  namespace: default
----
.. 클러스터 역할 바인딩을 적용합니다.
+
[source, console]
----
kubectl apply -f astracontrol-clusterrolebinding.yaml
----


. 토큰 암호 생성 및 적용:
+
.. 라는 토큰 비밀 파일을 만듭니다 `secret-astracontrol-service-account.yaml`.
+
[source, subs="specialcharacters,quotes"]
----
*secret-astracontrol-service-account.yaml*
----
+
[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: secret-astracontrol-service-account
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "astracontrol-service-account"
type: kubernetes.io/service-account-token
----
.. 토큰 암호 적용:
+
[source, console]
----
kubectl apply -f secret-astracontrol-service-account.yaml
----


. 토큰 암호를 에 추가하여 서비스 계정에 추가합니다 `secrets` 배열(다음 예제의 마지막 줄):
+
[source, console]
----
kubectl edit sa astracontrol-service-account
----
+
[source, subs="verbatim,quotes"]
----
apiVersion: v1
imagePullSecrets:
- name: astracontrol-service-account-dockercfg-48xhx
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"astracontrol-service-account","namespace":"default"}}
  creationTimestamp: "2023-06-14T15:25:45Z"
  name: astracontrol-service-account
  namespace: default
  resourceVersion: "2767069"
  uid: 2ce068c4-810e-4a96-ada3-49cbf9ec3f89
secrets:
- name: astracontrol-service-account-dockercfg-48xhx
*- name: secret-astracontrol-service-account*
----
. '<context>'을(를) 설치에 적합한 컨텍스트로 대체하여 서비스 계정 암호를 나열합니다.
+
[source, console]
----
kubectl get serviceaccount astracontrol-service-account --context <context> --namespace default -o json
----
+
출력의 끝은 다음과 유사합니다.

+
[listing]
----
"secrets": [
{ "name": "astracontrol-service-account-dockercfg-48xhx"},
{ "name": "secret-astracontrol-service-account"}
]
----
+
의 각 요소에 대한 인덱스입니다 `secrets` 어레이는 0으로 시작합니다. 위의 예에서 의 인덱스입니다 `astracontrol-service-account-dockercfg-48xhx` 는 0이고 의 인덱스입니다 `secret-astracontrol-service-account` 1입니다. 출력에서 서비스 계정의 인덱스 번호를 기록해 둡니다. 다음 단계에서는 이 인덱스 번호가 필요합니다.

. 다음과 같이 kubecononfig를 생성합니다.
+
.. 을 생성합니다 `create-kubeconfig.sh` 파일.
.. 대치 `TOKEN_INDEX` 다음 스크립트의 시작 부분에 올바른 값이 있습니다.
+
[source, subs="specialcharacters,quotes"]
----
*create-kubeconfig.sh*
----
+
[source, subs="verbatim,quotes"]
----
# Update these to match your environment.
# Replace TOKEN_INDEX with the correct value
# from the output in the previous step. If you
# didn't change anything else above, don't change
# anything else here.

SERVICE_ACCOUNT_NAME=astracontrol-service-account
NAMESPACE=default
NEW_CONTEXT=astracontrol
KUBECONFIG_FILE='kubeconfig-sa'

CONTEXT=$(kubectl config current-context)

SECRET_NAME=$(kubectl get serviceaccount ${SERVICE_ACCOUNT_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  *-o jsonpath='{.secrets[TOKEN_INDEX].name}')
TOKEN_DATA=$(kubectl get secret ${SECRET_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  -o jsonpath='{.data.token}')

TOKEN=$(echo ${TOKEN_DATA} | base64 -d)

# Create dedicated kubeconfig
# Create a full copy
kubectl config view --raw > ${KUBECONFIG_FILE}.full.tmp

# Switch working context to correct context
kubectl --kubeconfig ${KUBECONFIG_FILE}.full.tmp config use-context ${CONTEXT}

# Minify
kubectl --kubeconfig ${KUBECONFIG_FILE}.full.tmp \
  config view --flatten --minify > ${KUBECONFIG_FILE}.tmp

# Rename context
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  rename-context ${CONTEXT} ${NEW_CONTEXT}

# Create token user
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-credentials ${CONTEXT}-${NAMESPACE}-token-user \
  --token ${TOKEN}

# Set context to use token user
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-context ${NEW_CONTEXT} --user ${CONTEXT}-${NAMESPACE}-token-user

# Set context to correct namespace
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-context ${NEW_CONTEXT} --namespace ${NAMESPACE}

# Flatten/minify kubeconfig
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  view --flatten --minify > ${KUBECONFIG_FILE}

# Remove tmp
rm ${KUBECONFIG_FILE}.full.tmp
rm ${KUBECONFIG_FILE}.tmp
----
.. Kubernetes 클러스터에 적용할 명령을 소스 하십시오.
+
[source, console]
----
source create-kubeconfig.sh
----


. (선택 사항) kubeconfig의 이름을 클러스터의 의미 있는 이름으로 바꿉니다.
+
[listing]
----
mv kubeconfig-sa YOUR_CLUSTER_NAME_kubeconfig
----

