---
sidebar: sidebar 
permalink: release-notes/resolved-issues.html 
keywords: astra, control center, fixed bugs, fixes, resolved issues 
summary: 알려진 문제점은 이 제품 릴리스를 성공적으로 사용하지 못하게 만들 수 있는 문제를 식별합니다. 
---
= 해결된 문제
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


이러한 문제는 이 제품 릴리스에서 수정되었습니다.



== 예약된 백업의 일부로 추가 백업이 보존됩니다

Astra Control Center에 있는 하나 이상의 백업이 백업 스케줄에 보존되도록 지정된 수를 초과하여 보존되는 경우가 있습니다. 이러한 추가 백업은 예약된 백업의 일부로 삭제되어야 하지만 삭제되지는 않으며 "보류 중" 상태로 고착됩니다.



== Astra Control Center에서 PVCs를 사용하는 앱의 백업 또는 클론 생성이 실패합니다

10진수 단위로 생성된 볼륨이 Astra Control Center 백업 또는 클론 프로세스를 사용하여 실패합니다.



== Astra Control Center UI는 지속적인 볼륨 변경과 같은 앱 리소스의 변경 사항을 느리게 표시합니다

데이터 보호 작업(클론, 백업, 복원)과 후속 영구 볼륨 크기 조정 후 UI에 새 볼륨 크기가 표시되기까지 최대 20분이 지연됩니다. UI에서 이러한 지연은 앱 리소스가 추가되거나 수정될 때도 발생할 수 있습니다. 이 경우 데이터 보호 작업이 몇 분 내에 성공적으로 수행되며 스토리지 백엔드에 관리 소프트웨어를 사용하여 볼륨 크기 변경을 확인할 수 있습니다.



== 설치하는 동안 Astra Control Center 사용자 지정 리소스 정의에 의해 잘못된 클러스터 역할 바인딩이 생성되었습니다

이 릴리즈에서는 설치 중에 클러스터 역할 바인딩을 수정하는 패치가 더 이상 필요하지 않습니다.



== ASUP 컬렉션이 생성 또는 업로드 상태로 고착되었습니다

ASUP 포드가 중지되거나 다시 시작되면 ASUP 수집이 생성 또는 업로드 상태로 멈출 수 있습니다.



== 운영자로 구축된 앱 및 네임스페이스

배포되는 운영자와 앱은 동일한 네임스페이스를 사용해야 합니다. Astra Control은 네임스페이스당 하나의 운영자로 구축된 앱만 지원합니다.



== 자세한 내용을 확인하십시오

* link:../release-notes/known-issues.html["알려진 문제"]
* link:../release-notes/known-limitations.html["알려진 제한 사항"]
* link:../release-notes/known-issues-ads.html["Astra Data Store Preview 및 이 Astra Control Center 릴리스와 관련된 알려진 문제입니다"]

